# HTML5 runtime
# 
# Copyright (C) 2015 Zhang Ji Peng
# Contact: onecoolx@gmail.com

{
  'variables': {
    'webkit_dir': '../source/webkit-2.2.8/Source',
    'webview_dir': '../source/WebKit',
    'webcore_dir': '<(webkit_dir)/WebCore',
  },
  'targets': [
  {
    'target_name': 'demo',
    'type': 'executable',
    'dependencies': [
      'WebCore',
      'JavaScriptCore',
      'WTF',
    ],
    'include_dirs': [
      '<(webkit_dir)/',
      '<(webcore_dir)',
      '<(webcore_dir)/Generated',
      '<(webcore_dir)/Modules/battery',
      '<(webcore_dir)/Modules/filesystem',
      '<(webcore_dir)/Modules/gamepad',
      '<(webcore_dir)/Modules/geolocation',
      '<(webcore_dir)/Modules/indexeddb',
      '<(webcore_dir)/Modules/indieui',
      '<(webcore_dir)/Modules/mediasource',
      '<(webcore_dir)/Modules/mediastream',
      '<(webcore_dir)/Modules/navigatorcontentutils',
      '<(webcore_dir)/Modules/networkinfo',
      '<(webcore_dir)/Modules/notifications',
      '<(webcore_dir)/Modules/proximity',
      '<(webcore_dir)/Modules/quota',
      '<(webcore_dir)/Modules/speech',
      '<(webcore_dir)/Modules/vibration',
      '<(webcore_dir)/Modules/webaudio',
      '<(webcore_dir)/Modules/webdatabase',
      '<(webcore_dir)/Modules/websockets',
      '<(webcore_dir)/accessibility',
      '<(webcore_dir)/bindings',
      '<(webcore_dir)/bindings/generic',
      '<(webcore_dir)/bindings/js',
      '<(webcore_dir)/bridge',
      '<(webcore_dir)/bridge/c',
      '<(webcore_dir)/bridge/jsc',
      '<(webcore_dir)/css',
      '<(webcore_dir)/dom',
      '<(webcore_dir)/dom/default',
      '<(webcore_dir)/editing',
      '<(webcore_dir)/fileapi',
      '<(webcore_dir)/history',
      '<(webcore_dir)/html',
      '<(webcore_dir)/html/canvas',
      '<(webcore_dir)/html/forms',
      '<(webcore_dir)/html/parser',
      '<(webcore_dir)/html/shadow',
      '<(webcore_dir)/html/track',
      '<(webcore_dir)/inspector',
      '<(webcore_dir)/loader',
      '<(webcore_dir)/loader/appcache',
      '<(webcore_dir)/loader/archive',
      '<(webcore_dir)/loader/archive/mhtml',
      '<(webcore_dir)/loader/cache',
      '<(webcore_dir)/loader/icon',
      '<(webcore_dir)/mathml',
      '<(webcore_dir)/page',
      '<(webcore_dir)/page/animation',
      '<(webcore_dir)/page/scrolling',
      '<(webcore_dir)/platform',
      '<(webcore_dir)/platform/animation',
      '<(webcore_dir)/platform/audio',
      '<(webcore_dir)/platform/graphics',
      '<(webcore_dir)/platform/graphics/cpu/arm',
      '<(webcore_dir)/platform/graphics/cpu/arm/filters/',
      '<(webcore_dir)/platform/graphics/egl',
      '<(webcore_dir)/platform/graphics/filters',
      '<(webcore_dir)/platform/graphics/filters/texmap',
      '<(webcore_dir)/platform/graphics/freetype',
      '<(webcore_dir)/platform/graphics/gpu',
      '<(webcore_dir)/platform/graphics/opengl',
      '<(webcore_dir)/platform/graphics/surfaces',
      '<(webcore_dir)/platform/graphics/surfaces/egl',
      '<(webcore_dir)/platform/graphics/harfbuzz',
      '<(webcore_dir)/platform/graphics/harfbuzz/ng',
      '<(webcore_dir)/platform/graphics/opengl',
      '<(webcore_dir)/platform/graphics/texmap',
      '<(webcore_dir)/platform/graphics/opentype',
      '<(webcore_dir)/platform/graphics/transforms',
      '<(webcore_dir)/platform/image-decoders',
      '<(webcore_dir)/platform/image-decoders/bmp',
      '<(webcore_dir)/platform/image-decoders/gif',
      '<(webcore_dir)/platform/image-decoders/ico',
      '<(webcore_dir)/platform/image-decoders/jpeg',
      '<(webcore_dir)/platform/image-decoders/png',
      '<(webcore_dir)/platform/image-decoders/webp',
      '<(webcore_dir)/platform/leveldb',
      '<(webcore_dir)/platform/linux',
      '<(webcore_dir)/platform/mediastream',
      '<(webcore_dir)/platform/mediastream/gstreamer',
      '<(webcore_dir)/platform/mock',
      '<(webcore_dir)/platform/network',
      '<(webcore_dir)/platform/sql',
      '<(webcore_dir)/platform/text',
      '<(webcore_dir)/platform/text/transcoder',
      '<(webcore_dir)/plugins',
      '<(webcore_dir)/rendering',
      '<(webcore_dir)/rendering/mathml',
      '<(webcore_dir)/rendering/shapes',
      '<(webcore_dir)/rendering/style',
      '<(webcore_dir)/rendering/svg',
      '<(webcore_dir)/storage',
      '<(webcore_dir)/style',
      '<(webcore_dir)/svg',
      '<(webcore_dir)/svg/animation',
      '<(webcore_dir)/svg/graphics',
      '<(webcore_dir)/svg/graphics/filters',
      '<(webcore_dir)/svg/properties',
      '<(webcore_dir)/testing',
      '<(webcore_dir)/testing/js',
      '<(webcore_dir)/websockets',
      '<(webcore_dir)/workers',
      '<(webcore_dir)/xml',
      '<(webcore_dir)/xml/parser',
      '<(webview_dir)/',
      '<(webview_dir)/platform',
      '<(webview_dir)/platform/network',
      '<(webview_dir)/platform/graphics',
      '<(webview_dir)/WebCoreSupport',
      '<(webkit_dir)',
      '<(webkit_dir)/../../../include',
      '<(webkit_dir)/JavaScriptCore',
      '<(webkit_dir)/JavaScriptCore/API',
      '<(webkit_dir)/JavaScriptCore/ForwardingHeaders',
      '<(webkit_dir)/JavaScriptCore/assembler',
      '<(webkit_dir)/JavaScriptCore/bytecode',
      '<(webkit_dir)/JavaScriptCore/bytecompiler',
      '<(webkit_dir)/JavaScriptCore/debugger',
      '<(webkit_dir)/JavaScriptCore/dfg',
      '<(webkit_dir)/JavaScriptCore/disassembler',
      '<(webkit_dir)/JavaScriptCore/ftl',
      '<(webkit_dir)/JavaScriptCore/heap',
      '<(webkit_dir)/JavaScriptCore/interpreter',
      '<(webkit_dir)/JavaScriptCore/jit',
      '<(webkit_dir)/JavaScriptCore/llint',
      '<(webkit_dir)/JavaScriptCore/parser',
      '<(webkit_dir)/JavaScriptCore/profiler',
      '<(webkit_dir)/JavaScriptCore/runtime',
      '<(webkit_dir)/JavaScriptCore/tools',
      '<(webkit_dir)/JavaScriptCore/yarr',
      '<(webkit_dir)/WTF',
      '<(webkit_dir)/ThirdParty/ANGLE/include',
      '<(webkit_dir)/ThirdParty/ANGLE/include/GLSLANG',
      '<(webkit_dir)/ThirdParty/ANGLE/include/KHR',
    ],
    'sources': [
      'MainApp.cpp',
    ],
    'conditions': [
      ['OS=="win"', {
      'include_dirs': [
        '$(OutDir)/include',
        '$(OutDir)/include/uc',
        '$(OutDir)/include/i18n',
        '$(OutDir)/include/freetype',
        '$(OutDir)/include/harfbuzz',
        '$(OutDir)/WebCore',
        '$(OutDir)/../../build',
        ],
        'sources': [
          'win/Main.cpp',
        ],
        'msvs_disabled_warnings': [4800, 4805, 4355, 4396, 4244, 4251, 4101, 4291, 4344, 4065, 4018, 4503, 4996, 4005],
      }],
      ['OS=="linux"', {
        'include_dirs': [
          '$(builddir)/include',
          '$(builddir)/include/uv',
          '$(builddir)/include/uc',
          '$(builddir)/include/i18n',
          '$(builddir)/include/freetype',
          '$(builddir)/include/harfbuzz',
          '$(builddir)/WebCore',
          '$(builddir)/../../build',
        ],
        'sources': [
          'gtk/Main.cpp',
        ],
        'cflags': [
          '`pkg-config --cflags gtk+-2.0`',
        ],
        'cflags_cc': [
        ],
        'libraries': [
          '`pkg-config --libs gtk+-2.0`',
	      '-lEGL',
	      '-lGLESv2',
          '-lpthread',
          '-ldl',
          '-lz',
        ],
      }],
    ],
    'includes':[
      '../build/configs.gypi',
      '../build/defines.gypi',
    ],
  },
  ],
}

