set(ICUIO_DIR ${CMAKE_CURRENT_LIST_DIR}/source/io)

set(LIB_ICUIO icuio)

file(GLOB_RECURSE ICUIO_SOURCES ${ICUIO_DIR}/*.cpp)
file(GLOB_RECURSE ICUIO_HEADERS ${ICUIO_DIR}/unicode/*.h)

if(WIN32)
    set(ICUIO_SOURCES ${ICUIO_SOURCES} ${ICUIO_DIR}/io.rc)
endif(WIN32)

add_library(${LIB_ICUIO} SHARED ${ICUIO_SOURCES})

target_compile_definitions(${LIB_ICUIO} PRIVATE U_IO_IMPLEMENTATION)

target_link_libraries(${LIB_ICUIO} PRIVATE ${LIB_ICUUC} ${LIB_ICUI18N} ${CMAKE_DL_LIBS})

set_target_properties(${LIB_ICUIO} PROPERTIES VERSION ${VERSION_INFO}.${VERSION_MICRO} SOVERSION 1)

install(TARGETS ${LIB_ICUIO} LIBRARY DESTINATION lib ARCHIVE DESTINATION lib RUNTIME DESTINATION bin)

install(FILES ${ICUIO_HEADERS} DESTINATION include/unicode/)

include_directories(${ICUIO_DIR})
