set(ICUUC_DIR ${CMAKE_CURRENT_LIST_DIR}/source/common)

set(LIB_ICUUC icuuc)

file(GLOB_RECURSE ICUUC_SOURCES ${ICUUC_DIR}/*.cpp)
file(GLOB_RECURSE ICUUC_HEADERS ${ICUUC_DIR}/unicode/*.h)

if(WIN32)
    set(ICUUC_SOURCES ${ICUUC_SOURCES} ${ICUUC_DIR}/common.rc)
endif(WIN32)

add_library(${LIB_ICUUC} SHARED ${ICUUC_SOURCES})

target_compile_definitions(${LIB_ICUUC} PRIVATE U_COMMON_IMPLEMENTATION)

target_link_libraries(${LIB_ICUUC} PRIVATE ${LIB_ICUDT} ${CMAKE_DL_LIBS})

add_dependencies(${LIB_ICUUC} ${LIB_ICUDT})

set_target_properties(${LIB_ICUUC} PROPERTIES VERSION ${VERSION_INFO}.${VERSION_MICRO} SOVERSION 1)

install(TARGETS ${LIB_ICUUC} LIBRARY DESTINATION lib ARCHIVE DESTINATION lib RUNTIME DESTINATION bin)

install(FILES ${ICUUC_HEADERS} DESTINATION include/unicode/)

include_directories(${ICUUC_DIR})
