/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"


#if ENABLE(SVG)

#include "Document.h"
#include "Frame.h"
#include "SVGDocumentExtensions.h"
#include "SVGElement.h"
#include "SVGAnimatedTemplate.h"
#include "JSSVGPatternElement.h"

#include <wtf/GetPtr.h>

#include "CSSMutableStyleDeclaration.h"
#include "CSSStyleDeclaration.h"
#include "CSSValue.h"
#include "JSCSSStyleDeclaration.h"
#include "JSCSSValue.h"
#include "JSSVGAnimatedBoolean.h"
#include "JSSVGAnimatedEnumeration.h"
#include "JSSVGAnimatedLength.h"
#include "JSSVGAnimatedPreserveAspectRatio.h"
#include "JSSVGAnimatedRect.h"
#include "JSSVGAnimatedString.h"
#include "JSSVGAnimatedTransformList.h"
#include "JSSVGStringList.h"
#include "PlatformString.h"
#include "SVGPatternElement.h"
#include "SVGStringList.h"

using namespace KJS;

namespace WebCore {

/* Hash table */

static const HashEntry JSSVGPatternElementTableEntries[] =
{
    { "patternContentUnits", JSSVGPatternElement::PatternContentUnitsAttrNum, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "xmlspace", JSSVGPatternElement::XmlspaceAttrNum, DontDelete, 0, 0 },
    { "requiredFeatures", JSSVGPatternElement::RequiredFeaturesAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "y", JSSVGPatternElement::YAttrNum, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "xmllang", JSSVGPatternElement::XmllangAttrNum, DontDelete, 0, &JSSVGPatternElementTableEntries[22] },
    { 0, 0, 0, 0, 0 },
    { "style", JSSVGPatternElement::StyleAttrNum, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "x", JSSVGPatternElement::XAttrNum, DontDelete|ReadOnly, 0, &JSSVGPatternElementTableEntries[18] },
    { "patternTransform", JSSVGPatternElement::PatternTransformAttrNum, DontDelete|ReadOnly, 0, &JSSVGPatternElementTableEntries[19] },
    { "width", JSSVGPatternElement::WidthAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "patternUnits", JSSVGPatternElement::PatternUnitsAttrNum, DontDelete|ReadOnly, 0, &JSSVGPatternElementTableEntries[23] },
    { 0, 0, 0, 0, 0 },
    { "href", JSSVGPatternElement::HrefAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "requiredExtensions", JSSVGPatternElement::RequiredExtensionsAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "height", JSSVGPatternElement::HeightAttrNum, DontDelete|ReadOnly, 0, &JSSVGPatternElementTableEntries[20] },
    { "systemLanguage", JSSVGPatternElement::SystemLanguageAttrNum, DontDelete|ReadOnly, 0, &JSSVGPatternElementTableEntries[21] },
    { "externalResourcesRequired", JSSVGPatternElement::ExternalResourcesRequiredAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "className", JSSVGPatternElement::ClassNameAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "viewBox", JSSVGPatternElement::ViewBoxAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "preserveAspectRatio", JSSVGPatternElement::PreserveAspectRatioAttrNum, DontDelete|ReadOnly, 0, 0 }
};

static const HashTable JSSVGPatternElementTable = 
{
    2, 24, JSSVGPatternElementTableEntries, 18
};

/* Hash table for prototype */

static const HashEntry JSSVGPatternElementPrototypeTableEntries[] =
{
    { "getPresentationAttribute", JSSVGPatternElement::GetPresentationAttributeFuncNum, DontDelete|Function, 1, 0 },
    { "hasExtension", JSSVGPatternElement::HasExtensionFuncNum, DontDelete|Function, 1, 0 }
};

static const HashTable JSSVGPatternElementPrototypeTable = 
{
    2, 2, JSSVGPatternElementPrototypeTableEntries, 2
};

const ClassInfo JSSVGPatternElementPrototype::info = { "SVGPatternElementPrototype", 0, &JSSVGPatternElementPrototypeTable, 0 };

JSObject* JSSVGPatternElementPrototype::self(ExecState* exec)
{
    return KJS::cacheGlobalObject<JSSVGPatternElementPrototype>(exec, "[[JSSVGPatternElement.prototype]]");
}

bool JSSVGPatternElementPrototype::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticFunctionSlot<JSSVGPatternElementPrototypeFunction, JSObject>(exec, &JSSVGPatternElementPrototypeTable, this, propertyName, slot);
}

const ClassInfo JSSVGPatternElement::info = { "SVGPatternElement", &JSSVGElement::info, &JSSVGPatternElementTable, 0 };

JSSVGPatternElement::JSSVGPatternElement(ExecState* exec, SVGPatternElement* impl)
    : JSSVGElement(exec, impl)
{
    setPrototype(JSSVGPatternElementPrototype::self(exec));
}

bool JSSVGPatternElement::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGPatternElement, JSSVGElement>(exec, &JSSVGPatternElementTable, this, propertyName, slot);
}

JSValue* JSSVGPatternElement::getValueProperty(ExecState* exec, int token) const
{
    switch (token) {
    case PatternUnitsAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        RefPtr<SVGAnimatedEnumeration> obj = imp->patternUnitsAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case PatternContentUnitsAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        RefPtr<SVGAnimatedEnumeration> obj = imp->patternContentUnitsAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case PatternTransformAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        RefPtr<SVGAnimatedTransformList> obj = imp->patternTransformAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case XAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->xAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case YAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->yAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case WidthAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->widthAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case HeightAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->heightAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case HrefAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->hrefAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case RequiredFeaturesAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->requiredFeatures()), imp);
    }
    case RequiredExtensionsAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->requiredExtensions()), imp);
    }
    case SystemLanguageAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->systemLanguage()), imp);
    }
    case XmllangAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        return jsString(imp->xmllang());
    }
    case XmlspaceAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        return jsString(imp->xmlspace());
    }
    case ExternalResourcesRequiredAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        RefPtr<SVGAnimatedBoolean> obj = imp->externalResourcesRequiredAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case ClassNameAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->classNameAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case StyleAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->style()));
    }
    case ViewBoxAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        RefPtr<SVGAnimatedRect> obj = imp->viewBoxAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case PreserveAspectRatioAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        RefPtr<SVGAnimatedPreserveAspectRatio> obj = imp->preserveAspectRatioAnimated();
        return toJS(exec, obj.get(), imp);
    }
    }
    return 0;
}

void JSSVGPatternElement::put(ExecState* exec, const Identifier& propertyName, JSValue* value, int attr)
{
    lookupPut<JSSVGPatternElement, JSSVGElement>(exec, propertyName, value, attr, &JSSVGPatternElementTable, this);
}

void JSSVGPatternElement::putValueProperty(ExecState* exec, int token, JSValue* value, int /*attr*/)
{
    switch (token) {
    case XmllangAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        imp->setXmllang(value->toString(exec));
        break;
    }
    case XmlspaceAttrNum: {
        SVGPatternElement* imp = static_cast<SVGPatternElement*>(impl());

        imp->setXmlspace(value->toString(exec));
        break;
    }
    }
}

JSValue* JSSVGPatternElementPrototypeFunction::callAsFunction(ExecState* exec, JSObject* thisObj, const List& args)
{
    if (!thisObj->inherits(&JSSVGPatternElement::info))
      return throwError(exec, TypeError);

    JSSVGPatternElement* castedThisObj = static_cast<JSSVGPatternElement*>(thisObj);
    SVGPatternElement* imp = static_cast<SVGPatternElement*>(castedThisObj->impl());

    switch (id) {
    case JSSVGPatternElement::HasExtensionFuncNum: {
        String extension = args[0]->toString(exec);


        KJS::JSValue* result = jsBoolean(imp->hasExtension(extension));
        return result;
    }
    case JSSVGPatternElement::GetPresentationAttributeFuncNum: {
        String name = args[0]->toString(exec);


        KJS::JSValue* result = toJS(exec, WTF::getPtr(imp->getPresentationAttribute(name)));
        return result;
    }
    }
    return 0;
}

}

#endif // ENABLE(SVG)
