/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"


#if ENABLE(SVG)

#include "Document.h"
#include "Frame.h"
#include "SVGDocumentExtensions.h"
#include "SVGElement.h"
#include "SVGAnimatedTemplate.h"
#include "JSSVGMaskElement.h"

#include <wtf/GetPtr.h>

#include "CSSMutableStyleDeclaration.h"
#include "CSSStyleDeclaration.h"
#include "CSSValue.h"
#include "JSCSSStyleDeclaration.h"
#include "JSCSSValue.h"
#include "JSSVGAnimatedBoolean.h"
#include "JSSVGAnimatedEnumeration.h"
#include "JSSVGAnimatedLength.h"
#include "JSSVGAnimatedString.h"
#include "JSSVGStringList.h"
#include "PlatformString.h"
#include "SVGMaskElement.h"
#include "SVGStringList.h"

using namespace KJS;

namespace WebCore {

/* Hash table */

static const HashEntry JSSVGMaskElementTableEntries[] =
{
    { "xmlspace", JSSVGMaskElement::XmlspaceAttrNum, DontDelete, 0, 0 },
    { "width", JSSVGMaskElement::WidthAttrNum, DontDelete|ReadOnly, 0, &JSSVGMaskElementTableEntries[15] },
    { "style", JSSVGMaskElement::StyleAttrNum, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "maskContentUnits", JSSVGMaskElement::MaskContentUnitsAttrNum, DontDelete|ReadOnly, 0, &JSSVGMaskElementTableEntries[16] },
    { "maskUnits", JSSVGMaskElement::MaskUnitsAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "xmllang", JSSVGMaskElement::XmllangAttrNum, DontDelete, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "className", JSSVGMaskElement::ClassNameAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "x", JSSVGMaskElement::XAttrNum, DontDelete|ReadOnly, 0, &JSSVGMaskElementTableEntries[14] },
    { 0, 0, 0, 0, 0 },
    { "requiredExtensions", JSSVGMaskElement::RequiredExtensionsAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "y", JSSVGMaskElement::YAttrNum, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "height", JSSVGMaskElement::HeightAttrNum, DontDelete|ReadOnly, 0, &JSSVGMaskElementTableEntries[17] },
    { "requiredFeatures", JSSVGMaskElement::RequiredFeaturesAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "systemLanguage", JSSVGMaskElement::SystemLanguageAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "externalResourcesRequired", JSSVGMaskElement::ExternalResourcesRequiredAttrNum, DontDelete|ReadOnly, 0, 0 }
};

static const HashTable JSSVGMaskElementTable = 
{
    2, 18, JSSVGMaskElementTableEntries, 14
};

/* Hash table for prototype */

static const HashEntry JSSVGMaskElementPrototypeTableEntries[] =
{
    { "getPresentationAttribute", JSSVGMaskElement::GetPresentationAttributeFuncNum, DontDelete|Function, 1, 0 },
    { "hasExtension", JSSVGMaskElement::HasExtensionFuncNum, DontDelete|Function, 1, 0 }
};

static const HashTable JSSVGMaskElementPrototypeTable = 
{
    2, 2, JSSVGMaskElementPrototypeTableEntries, 2
};

const ClassInfo JSSVGMaskElementPrototype::info = { "SVGMaskElementPrototype", 0, &JSSVGMaskElementPrototypeTable, 0 };

JSObject* JSSVGMaskElementPrototype::self(ExecState* exec)
{
    return KJS::cacheGlobalObject<JSSVGMaskElementPrototype>(exec, "[[JSSVGMaskElement.prototype]]");
}

bool JSSVGMaskElementPrototype::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticFunctionSlot<JSSVGMaskElementPrototypeFunction, JSObject>(exec, &JSSVGMaskElementPrototypeTable, this, propertyName, slot);
}

const ClassInfo JSSVGMaskElement::info = { "SVGMaskElement", &JSSVGElement::info, &JSSVGMaskElementTable, 0 };

JSSVGMaskElement::JSSVGMaskElement(ExecState* exec, SVGMaskElement* impl)
    : JSSVGElement(exec, impl)
{
    setPrototype(JSSVGMaskElementPrototype::self(exec));
}

bool JSSVGMaskElement::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGMaskElement, JSSVGElement>(exec, &JSSVGMaskElementTable, this, propertyName, slot);
}

JSValue* JSSVGMaskElement::getValueProperty(ExecState* exec, int token) const
{
    switch (token) {
    case MaskUnitsAttrNum: {
        SVGMaskElement* imp = static_cast<SVGMaskElement*>(impl());

        RefPtr<SVGAnimatedEnumeration> obj = imp->maskUnitsAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case MaskContentUnitsAttrNum: {
        SVGMaskElement* imp = static_cast<SVGMaskElement*>(impl());

        RefPtr<SVGAnimatedEnumeration> obj = imp->maskContentUnitsAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case XAttrNum: {
        SVGMaskElement* imp = static_cast<SVGMaskElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->xAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case YAttrNum: {
        SVGMaskElement* imp = static_cast<SVGMaskElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->yAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case WidthAttrNum: {
        SVGMaskElement* imp = static_cast<SVGMaskElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->widthAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case HeightAttrNum: {
        SVGMaskElement* imp = static_cast<SVGMaskElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->heightAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case RequiredFeaturesAttrNum: {
        SVGMaskElement* imp = static_cast<SVGMaskElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->requiredFeatures()), imp);
    }
    case RequiredExtensionsAttrNum: {
        SVGMaskElement* imp = static_cast<SVGMaskElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->requiredExtensions()), imp);
    }
    case SystemLanguageAttrNum: {
        SVGMaskElement* imp = static_cast<SVGMaskElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->systemLanguage()), imp);
    }
    case XmllangAttrNum: {
        SVGMaskElement* imp = static_cast<SVGMaskElement*>(impl());

        return jsString(imp->xmllang());
    }
    case XmlspaceAttrNum: {
        SVGMaskElement* imp = static_cast<SVGMaskElement*>(impl());

        return jsString(imp->xmlspace());
    }
    case ExternalResourcesRequiredAttrNum: {
        SVGMaskElement* imp = static_cast<SVGMaskElement*>(impl());

        RefPtr<SVGAnimatedBoolean> obj = imp->externalResourcesRequiredAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case ClassNameAttrNum: {
        SVGMaskElement* imp = static_cast<SVGMaskElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->classNameAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case StyleAttrNum: {
        SVGMaskElement* imp = static_cast<SVGMaskElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->style()));
    }
    }
    return 0;
}

void JSSVGMaskElement::put(ExecState* exec, const Identifier& propertyName, JSValue* value, int attr)
{
    lookupPut<JSSVGMaskElement, JSSVGElement>(exec, propertyName, value, attr, &JSSVGMaskElementTable, this);
}

void JSSVGMaskElement::putValueProperty(ExecState* exec, int token, JSValue* value, int /*attr*/)
{
    switch (token) {
    case XmllangAttrNum: {
        SVGMaskElement* imp = static_cast<SVGMaskElement*>(impl());

        imp->setXmllang(value->toString(exec));
        break;
    }
    case XmlspaceAttrNum: {
        SVGMaskElement* imp = static_cast<SVGMaskElement*>(impl());

        imp->setXmlspace(value->toString(exec));
        break;
    }
    }
}

JSValue* JSSVGMaskElementPrototypeFunction::callAsFunction(ExecState* exec, JSObject* thisObj, const List& args)
{
    if (!thisObj->inherits(&JSSVGMaskElement::info))
      return throwError(exec, TypeError);

    JSSVGMaskElement* castedThisObj = static_cast<JSSVGMaskElement*>(thisObj);
    SVGMaskElement* imp = static_cast<SVGMaskElement*>(castedThisObj->impl());

    switch (id) {
    case JSSVGMaskElement::HasExtensionFuncNum: {
        String extension = args[0]->toString(exec);


        KJS::JSValue* result = jsBoolean(imp->hasExtension(extension));
        return result;
    }
    case JSSVGMaskElement::GetPresentationAttributeFuncNum: {
        String name = args[0]->toString(exec);


        KJS::JSValue* result = toJS(exec, WTF::getPtr(imp->getPresentationAttribute(name)));
        return result;
    }
    }
    return 0;
}

}

#endif // ENABLE(SVG)
