/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"


#if ENABLE(SVG) && ENABLE(SVG_EXPERIMENTAL_FEATURES)

#include "Document.h"
#include "Frame.h"
#include "SVGDocumentExtensions.h"
#include "SVGElement.h"
#include "SVGAnimatedTemplate.h"
#include "JSSVGFETileElement.h"

#include <wtf/GetPtr.h>

#include "CSSMutableStyleDeclaration.h"
#include "CSSStyleDeclaration.h"
#include "CSSValue.h"
#include "JSCSSStyleDeclaration.h"
#include "JSCSSValue.h"
#include "JSSVGAnimatedLength.h"
#include "JSSVGAnimatedString.h"
#include "SVGFETileElement.h"

using namespace KJS;

namespace WebCore {

/* Hash table */

static const HashEntry JSSVGFETileElementTableEntries[] =
{
    { 0, 0, 0, 0, 0 },
    { "x", JSSVGFETileElement::XAttrNum, DontDelete|ReadOnly, 0, &JSSVGFETileElementTableEntries[8] },
    { "className", JSSVGFETileElement::ClassNameAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "width", JSSVGFETileElement::WidthAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "y", JSSVGFETileElement::YAttrNum, DontDelete|ReadOnly, 0, &JSSVGFETileElementTableEntries[10] },
    { 0, 0, 0, 0, 0 },
    { "in1", JSSVGFETileElement::In1AttrNum, DontDelete|ReadOnly, 0, &JSSVGFETileElementTableEntries[9] },
    { 0, 0, 0, 0, 0 },
    { "height", JSSVGFETileElement::HeightAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "result", JSSVGFETileElement::ResultAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "style", JSSVGFETileElement::StyleAttrNum, DontDelete|ReadOnly, 0, 0 }
};

static const HashTable JSSVGFETileElementTable = 
{
    2, 11, JSSVGFETileElementTableEntries, 8
};

/* Hash table for prototype */

static const HashEntry JSSVGFETileElementPrototypeTableEntries[] =
{
    { "getPresentationAttribute", JSSVGFETileElement::GetPresentationAttributeFuncNum, DontDelete|Function, 1, 0 }
};

static const HashTable JSSVGFETileElementPrototypeTable = 
{
    2, 1, JSSVGFETileElementPrototypeTableEntries, 1
};

const ClassInfo JSSVGFETileElementPrototype::info = { "SVGFETileElementPrototype", 0, &JSSVGFETileElementPrototypeTable, 0 };

JSObject* JSSVGFETileElementPrototype::self(ExecState* exec)
{
    return KJS::cacheGlobalObject<JSSVGFETileElementPrototype>(exec, "[[JSSVGFETileElement.prototype]]");
}

bool JSSVGFETileElementPrototype::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticFunctionSlot<JSSVGFETileElementPrototypeFunction, JSObject>(exec, &JSSVGFETileElementPrototypeTable, this, propertyName, slot);
}

const ClassInfo JSSVGFETileElement::info = { "SVGFETileElement", &JSSVGElement::info, &JSSVGFETileElementTable, 0 };

JSSVGFETileElement::JSSVGFETileElement(ExecState* exec, SVGFETileElement* impl)
    : JSSVGElement(exec, impl)
{
    setPrototype(JSSVGFETileElementPrototype::self(exec));
}

bool JSSVGFETileElement::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGFETileElement, JSSVGElement>(exec, &JSSVGFETileElementTable, this, propertyName, slot);
}

JSValue* JSSVGFETileElement::getValueProperty(ExecState* exec, int token) const
{
    switch (token) {
    case In1AttrNum: {
        SVGFETileElement* imp = static_cast<SVGFETileElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->in1Animated();
        return toJS(exec, obj.get(), imp);
    }
    case XAttrNum: {
        SVGFETileElement* imp = static_cast<SVGFETileElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->xAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case YAttrNum: {
        SVGFETileElement* imp = static_cast<SVGFETileElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->yAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case WidthAttrNum: {
        SVGFETileElement* imp = static_cast<SVGFETileElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->widthAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case HeightAttrNum: {
        SVGFETileElement* imp = static_cast<SVGFETileElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->heightAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case ResultAttrNum: {
        SVGFETileElement* imp = static_cast<SVGFETileElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->resultAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case ClassNameAttrNum: {
        SVGFETileElement* imp = static_cast<SVGFETileElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->classNameAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case StyleAttrNum: {
        SVGFETileElement* imp = static_cast<SVGFETileElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->style()));
    }
    }
    return 0;
}

JSValue* JSSVGFETileElementPrototypeFunction::callAsFunction(ExecState* exec, JSObject* thisObj, const List& args)
{
    if (!thisObj->inherits(&JSSVGFETileElement::info))
      return throwError(exec, TypeError);

    JSSVGFETileElement* castedThisObj = static_cast<JSSVGFETileElement*>(thisObj);
    SVGFETileElement* imp = static_cast<SVGFETileElement*>(castedThisObj->impl());

    switch (id) {
    case JSSVGFETileElement::GetPresentationAttributeFuncNum: {
        String name = args[0]->toString(exec);


        KJS::JSValue* result = toJS(exec, WTF::getPtr(imp->getPresentationAttribute(name)));
        return result;
    }
    }
    return 0;
}

}

#endif // ENABLE(SVG) && ENABLE(SVG_EXPERIMENTAL_FEATURES)
