/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"


#if ENABLE(SVG)

#include "Document.h"
#include "Frame.h"
#include "SVGDocumentExtensions.h"
#include "SVGElement.h"
#include "SVGAnimatedTemplate.h"
#include "JSSVGTextPathElement.h"

#include <wtf/GetPtr.h>

#include "JSSVGAnimatedEnumeration.h"
#include "JSSVGAnimatedLength.h"
#include "JSSVGAnimatedString.h"
#include "SVGTextPathElement.h"

using namespace KJS;

namespace WebCore {

/* Hash table */

static const HashEntry JSSVGTextPathElementTableEntries[] =
{
    { 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "href", JSSVGTextPathElement::HrefAttrNum, DontDelete|ReadOnly, 0, &JSSVGTextPathElementTableEntries[6] },
    { "spacing", JSSVGTextPathElement::SpacingAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "startOffset", JSSVGTextPathElement::StartOffsetAttrNum, DontDelete|ReadOnly, 0, &JSSVGTextPathElementTableEntries[5] },
    { "method", JSSVGTextPathElement::MethodAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "constructor", JSSVGTextPathElement::ConstructorAttrNum, DontDelete|DontEnum|ReadOnly, 0, 0 }
};

static const HashTable JSSVGTextPathElementTable = 
{
    2, 7, JSSVGTextPathElementTableEntries, 5
};

/* Hash table for constructor */

static const HashEntry JSSVGTextPathElementConstructorTableEntries[] =
{
    { "TEXTPATH_METHODTYPE_UNKNOWN", SVGTextPathElement::TEXTPATH_METHODTYPE_UNKNOWN, DontDelete|ReadOnly, 0, 0 },
    { "TEXTPATH_SPACINGTYPE_UNKNOWN", SVGTextPathElement::TEXTPATH_SPACINGTYPE_UNKNOWN, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "TEXTPATH_METHODTYPE_ALIGN", SVGTextPathElement::TEXTPATH_METHODTYPE_ALIGN, DontDelete|ReadOnly, 0, &JSSVGTextPathElementConstructorTableEntries[6] },
    { "TEXTPATH_METHODTYPE_STRETCH", SVGTextPathElement::TEXTPATH_METHODTYPE_STRETCH, DontDelete|ReadOnly, 0, 0 },
    { "TEXTPATH_SPACINGTYPE_EXACT", SVGTextPathElement::TEXTPATH_SPACINGTYPE_EXACT, DontDelete|ReadOnly, 0, 0 },
    { "TEXTPATH_SPACINGTYPE_AUTO", SVGTextPathElement::TEXTPATH_SPACINGTYPE_AUTO, DontDelete|ReadOnly, 0, 0 }
};

static const HashTable JSSVGTextPathElementConstructorTable = 
{
    2, 7, JSSVGTextPathElementConstructorTableEntries, 6
};

class JSSVGTextPathElementConstructor : public DOMObject {
public:
    JSSVGTextPathElementConstructor(ExecState* exec)
    {
        setPrototype(exec->lexicalInterpreter()->builtinObjectPrototype());
        putDirect(exec->propertyNames().prototype, JSSVGTextPathElementPrototype::self(exec), None);
    }
    virtual bool getOwnPropertySlot(ExecState*, const Identifier&, PropertySlot&);
    JSValue* getValueProperty(ExecState*, int token) const;
    virtual const ClassInfo* classInfo() const { return &info; }
    static const ClassInfo info;

    virtual bool implementsHasInstance() const { return true; }
};

const ClassInfo JSSVGTextPathElementConstructor::info = { "SVGTextPathElementConstructor", 0, &JSSVGTextPathElementConstructorTable, 0 };

bool JSSVGTextPathElementConstructor::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGTextPathElementConstructor, DOMObject>(exec, &JSSVGTextPathElementConstructorTable, this, propertyName, slot);
}

JSValue* JSSVGTextPathElementConstructor::getValueProperty(ExecState*, int token) const
{
    // The token is the numeric value of its associated constant
    return jsNumber(token);
}

/* Hash table for prototype */

static const HashEntry JSSVGTextPathElementPrototypeTableEntries[] =
{
    { "TEXTPATH_METHODTYPE_UNKNOWN", SVGTextPathElement::TEXTPATH_METHODTYPE_UNKNOWN, DontDelete|ReadOnly, 0, 0 },
    { "TEXTPATH_SPACINGTYPE_UNKNOWN", SVGTextPathElement::TEXTPATH_SPACINGTYPE_UNKNOWN, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "TEXTPATH_METHODTYPE_ALIGN", SVGTextPathElement::TEXTPATH_METHODTYPE_ALIGN, DontDelete|ReadOnly, 0, &JSSVGTextPathElementPrototypeTableEntries[6] },
    { "TEXTPATH_METHODTYPE_STRETCH", SVGTextPathElement::TEXTPATH_METHODTYPE_STRETCH, DontDelete|ReadOnly, 0, 0 },
    { "TEXTPATH_SPACINGTYPE_EXACT", SVGTextPathElement::TEXTPATH_SPACINGTYPE_EXACT, DontDelete|ReadOnly, 0, 0 },
    { "TEXTPATH_SPACINGTYPE_AUTO", SVGTextPathElement::TEXTPATH_SPACINGTYPE_AUTO, DontDelete|ReadOnly, 0, 0 }
};

static const HashTable JSSVGTextPathElementPrototypeTable = 
{
    2, 7, JSSVGTextPathElementPrototypeTableEntries, 6
};

const ClassInfo JSSVGTextPathElementPrototype::info = { "SVGTextPathElementPrototype", 0, &JSSVGTextPathElementPrototypeTable, 0 };

JSObject* JSSVGTextPathElementPrototype::self(ExecState* exec)
{
    return KJS::cacheGlobalObject<JSSVGTextPathElementPrototype>(exec, "[[JSSVGTextPathElement.prototype]]");
}

bool JSSVGTextPathElementPrototype::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGTextPathElementPrototype, JSObject>(exec, &JSSVGTextPathElementPrototypeTable, this, propertyName, slot);
}

JSValue* JSSVGTextPathElementPrototype::getValueProperty(ExecState*, int token) const
{
    // The token is the numeric value of its associated constant
    return jsNumber(token);
}

const ClassInfo JSSVGTextPathElement::info = { "SVGTextPathElement", &JSSVGTextContentElement::info, &JSSVGTextPathElementTable, 0 };

JSSVGTextPathElement::JSSVGTextPathElement(ExecState* exec, SVGTextPathElement* impl)
    : JSSVGTextContentElement(exec, impl)
{
    setPrototype(JSSVGTextPathElementPrototype::self(exec));
}

bool JSSVGTextPathElement::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGTextPathElement, JSSVGTextContentElement>(exec, &JSSVGTextPathElementTable, this, propertyName, slot);
}

JSValue* JSSVGTextPathElement::getValueProperty(ExecState* exec, int token) const
{
    switch (token) {
    case StartOffsetAttrNum: {
        SVGTextPathElement* imp = static_cast<SVGTextPathElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->startOffsetAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case MethodAttrNum: {
        SVGTextPathElement* imp = static_cast<SVGTextPathElement*>(impl());

        RefPtr<SVGAnimatedEnumeration> obj = imp->methodAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case SpacingAttrNum: {
        SVGTextPathElement* imp = static_cast<SVGTextPathElement*>(impl());

        RefPtr<SVGAnimatedEnumeration> obj = imp->spacingAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case HrefAttrNum: {
        SVGTextPathElement* imp = static_cast<SVGTextPathElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->hrefAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case ConstructorAttrNum:
        return getConstructor(exec);
    }
    return 0;
}

JSValue* JSSVGTextPathElement::getConstructor(ExecState* exec)
{
    return KJS::cacheGlobalObject<JSSVGTextPathElementConstructor>(exec, "[[SVGTextPathElement.constructor]]");
}

}

#endif // ENABLE(SVG)
