/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"


#if ENABLE(SVG) && ENABLE(SVG_EXPERIMENTAL_FEATURES)

#include "Document.h"
#include "Frame.h"
#include "SVGDocumentExtensions.h"
#include "SVGElement.h"
#include "SVGAnimatedTemplate.h"
#include "JSSVGFEColorMatrixElement.h"

#include <wtf/GetPtr.h>

#include "CSSMutableStyleDeclaration.h"
#include "CSSStyleDeclaration.h"
#include "CSSValue.h"
#include "JSCSSStyleDeclaration.h"
#include "JSCSSValue.h"
#include "JSSVGAnimatedEnumeration.h"
#include "JSSVGAnimatedLength.h"
#include "JSSVGAnimatedNumberList.h"
#include "JSSVGAnimatedString.h"
#include "SVGFEColorMatrixElement.h"

using namespace KJS;

namespace WebCore {

/* Hash table */

static const HashEntry JSSVGFEColorMatrixElementTableEntries[] =
{
    { 0, 0, 0, 0, 0 },
    { "values", JSSVGFEColorMatrixElement::ValuesAttrNum, DontDelete|ReadOnly, 0, &JSSVGFEColorMatrixElementTableEntries[11] },
    { 0, 0, 0, 0, 0 },
    { "height", JSSVGFEColorMatrixElement::HeightAttrNum, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "className", JSSVGFEColorMatrixElement::ClassNameAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "type", JSSVGFEColorMatrixElement::TypeAttrNum, DontDelete|ReadOnly, 0, &JSSVGFEColorMatrixElementTableEntries[12] },
    { "in1", JSSVGFEColorMatrixElement::In1AttrNum, DontDelete|ReadOnly, 0, &JSSVGFEColorMatrixElementTableEntries[13] },
    { 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "result", JSSVGFEColorMatrixElement::ResultAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "x", JSSVGFEColorMatrixElement::XAttrNum, DontDelete|ReadOnly, 0, &JSSVGFEColorMatrixElementTableEntries[15] },
    { "y", JSSVGFEColorMatrixElement::YAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "width", JSSVGFEColorMatrixElement::WidthAttrNum, DontDelete|ReadOnly, 0, &JSSVGFEColorMatrixElementTableEntries[14] },
    { "style", JSSVGFEColorMatrixElement::StyleAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "constructor", JSSVGFEColorMatrixElement::ConstructorAttrNum, DontDelete|DontEnum|ReadOnly, 0, 0 }
};

static const HashTable JSSVGFEColorMatrixElementTable = 
{
    2, 16, JSSVGFEColorMatrixElementTableEntries, 11
};

/* Hash table for constructor */

static const HashEntry JSSVGFEColorMatrixElementConstructorTableEntries[] =
{
    { "SVG_FECOLORMATRIX_TYPE_UNKNOWN", WebCore::SVG_FECOLORMATRIX_TYPE_UNKNOWN, DontDelete|ReadOnly, 0, 0 },
    { "SVG_FECOLORMATRIX_TYPE_SATURATE", WebCore::SVG_FECOLORMATRIX_TYPE_SATURATE, DontDelete|ReadOnly, 0, &JSSVGFEColorMatrixElementConstructorTableEntries[5] },
    { 0, 0, 0, 0, 0 },
    { "SVG_FECOLORMATRIX_TYPE_MATRIX", WebCore::SVG_FECOLORMATRIX_TYPE_MATRIX, DontDelete|ReadOnly, 0, 0 },
    { "SVG_FECOLORMATRIX_TYPE_HUEROTATE", WebCore::SVG_FECOLORMATRIX_TYPE_HUEROTATE, DontDelete|ReadOnly, 0, 0 },
    { "SVG_FECOLORMATRIX_TYPE_LUMINANCETOALPHA", WebCore::SVG_FECOLORMATRIX_TYPE_LUMINANCETOALPHA, DontDelete|ReadOnly, 0, 0 }
};

static const HashTable JSSVGFEColorMatrixElementConstructorTable = 
{
    2, 6, JSSVGFEColorMatrixElementConstructorTableEntries, 5
};

class JSSVGFEColorMatrixElementConstructor : public DOMObject {
public:
    JSSVGFEColorMatrixElementConstructor(ExecState* exec)
    {
        setPrototype(exec->lexicalInterpreter()->builtinObjectPrototype());
        putDirect(exec->propertyNames().prototype, JSSVGFEColorMatrixElementPrototype::self(exec), None);
    }
    virtual bool getOwnPropertySlot(ExecState*, const Identifier&, PropertySlot&);
    JSValue* getValueProperty(ExecState*, int token) const;
    virtual const ClassInfo* classInfo() const { return &info; }
    static const ClassInfo info;

    virtual bool implementsHasInstance() const { return true; }
};

const ClassInfo JSSVGFEColorMatrixElementConstructor::info = { "SVGFEColorMatrixElementConstructor", 0, &JSSVGFEColorMatrixElementConstructorTable, 0 };

bool JSSVGFEColorMatrixElementConstructor::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGFEColorMatrixElementConstructor, DOMObject>(exec, &JSSVGFEColorMatrixElementConstructorTable, this, propertyName, slot);
}

JSValue* JSSVGFEColorMatrixElementConstructor::getValueProperty(ExecState*, int token) const
{
    // The token is the numeric value of its associated constant
    return jsNumber(token);
}

/* Hash table for prototype */

static const HashEntry JSSVGFEColorMatrixElementPrototypeTableEntries[] =
{
    { "SVG_FECOLORMATRIX_TYPE_HUEROTATE", WebCore::SVG_FECOLORMATRIX_TYPE_HUEROTATE, DontDelete|ReadOnly, 0, &JSSVGFEColorMatrixElementPrototypeTableEntries[6] },
    { "SVG_FECOLORMATRIX_TYPE_MATRIX", WebCore::SVG_FECOLORMATRIX_TYPE_MATRIX, DontDelete|ReadOnly, 0, 0 },
    { "SVG_FECOLORMATRIX_TYPE_LUMINANCETOALPHA", WebCore::SVG_FECOLORMATRIX_TYPE_LUMINANCETOALPHA, DontDelete|ReadOnly, 0, 0 },
    { "SVG_FECOLORMATRIX_TYPE_UNKNOWN", WebCore::SVG_FECOLORMATRIX_TYPE_UNKNOWN, DontDelete|ReadOnly, 0, 0 },
    { "SVG_FECOLORMATRIX_TYPE_SATURATE", WebCore::SVG_FECOLORMATRIX_TYPE_SATURATE, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "getPresentationAttribute", JSSVGFEColorMatrixElement::GetPresentationAttributeFuncNum, DontDelete|Function, 1, 0 }
};

static const HashTable JSSVGFEColorMatrixElementPrototypeTable = 
{
    2, 7, JSSVGFEColorMatrixElementPrototypeTableEntries, 6
};

const ClassInfo JSSVGFEColorMatrixElementPrototype::info = { "SVGFEColorMatrixElementPrototype", 0, &JSSVGFEColorMatrixElementPrototypeTable, 0 };

JSObject* JSSVGFEColorMatrixElementPrototype::self(ExecState* exec)
{
    return KJS::cacheGlobalObject<JSSVGFEColorMatrixElementPrototype>(exec, "[[JSSVGFEColorMatrixElement.prototype]]");
}

bool JSSVGFEColorMatrixElementPrototype::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticPropertySlot<JSSVGFEColorMatrixElementPrototypeFunction, JSSVGFEColorMatrixElementPrototype, JSObject>(exec, &JSSVGFEColorMatrixElementPrototypeTable, this, propertyName, slot);
}

JSValue* JSSVGFEColorMatrixElementPrototype::getValueProperty(ExecState*, int token) const
{
    // The token is the numeric value of its associated constant
    return jsNumber(token);
}

const ClassInfo JSSVGFEColorMatrixElement::info = { "SVGFEColorMatrixElement", &JSSVGElement::info, &JSSVGFEColorMatrixElementTable, 0 };

JSSVGFEColorMatrixElement::JSSVGFEColorMatrixElement(ExecState* exec, SVGFEColorMatrixElement* impl)
    : JSSVGElement(exec, impl)
{
    setPrototype(JSSVGFEColorMatrixElementPrototype::self(exec));
}

bool JSSVGFEColorMatrixElement::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGFEColorMatrixElement, JSSVGElement>(exec, &JSSVGFEColorMatrixElementTable, this, propertyName, slot);
}

JSValue* JSSVGFEColorMatrixElement::getValueProperty(ExecState* exec, int token) const
{
    switch (token) {
    case In1AttrNum: {
        SVGFEColorMatrixElement* imp = static_cast<SVGFEColorMatrixElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->in1Animated();
        return toJS(exec, obj.get(), imp);
    }
    case TypeAttrNum: {
        SVGFEColorMatrixElement* imp = static_cast<SVGFEColorMatrixElement*>(impl());

        RefPtr<SVGAnimatedEnumeration> obj = imp->typeAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case ValuesAttrNum: {
        SVGFEColorMatrixElement* imp = static_cast<SVGFEColorMatrixElement*>(impl());

        RefPtr<SVGAnimatedNumberList> obj = imp->valuesAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case XAttrNum: {
        SVGFEColorMatrixElement* imp = static_cast<SVGFEColorMatrixElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->xAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case YAttrNum: {
        SVGFEColorMatrixElement* imp = static_cast<SVGFEColorMatrixElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->yAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case WidthAttrNum: {
        SVGFEColorMatrixElement* imp = static_cast<SVGFEColorMatrixElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->widthAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case HeightAttrNum: {
        SVGFEColorMatrixElement* imp = static_cast<SVGFEColorMatrixElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->heightAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case ResultAttrNum: {
        SVGFEColorMatrixElement* imp = static_cast<SVGFEColorMatrixElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->resultAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case ClassNameAttrNum: {
        SVGFEColorMatrixElement* imp = static_cast<SVGFEColorMatrixElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->classNameAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case StyleAttrNum: {
        SVGFEColorMatrixElement* imp = static_cast<SVGFEColorMatrixElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->style()));
    }
    case ConstructorAttrNum:
        return getConstructor(exec);
    }
    return 0;
}

JSValue* JSSVGFEColorMatrixElement::getConstructor(ExecState* exec)
{
    return KJS::cacheGlobalObject<JSSVGFEColorMatrixElementConstructor>(exec, "[[SVGFEColorMatrixElement.constructor]]");
}
JSValue* JSSVGFEColorMatrixElementPrototypeFunction::callAsFunction(ExecState* exec, JSObject* thisObj, const List& args)
{
    if (!thisObj->inherits(&JSSVGFEColorMatrixElement::info))
      return throwError(exec, TypeError);

    JSSVGFEColorMatrixElement* castedThisObj = static_cast<JSSVGFEColorMatrixElement*>(thisObj);
    SVGFEColorMatrixElement* imp = static_cast<SVGFEColorMatrixElement*>(castedThisObj->impl());

    switch (id) {
    case JSSVGFEColorMatrixElement::GetPresentationAttributeFuncNum: {
        String name = args[0]->toString(exec);


        KJS::JSValue* result = toJS(exec, WTF::getPtr(imp->getPresentationAttribute(name)));
        return result;
    }
    }
    return 0;
}

}

#endif // ENABLE(SVG) && ENABLE(SVG_EXPERIMENTAL_FEATURES)
