/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"


#if ENABLE(SVG)

#include "Document.h"
#include "Frame.h"
#include "SVGDocumentExtensions.h"
#include "SVGElement.h"
#include "SVGAnimatedTemplate.h"
#include "JSSVGLineElement.h"

#include <wtf/GetPtr.h>

#include "CSSMutableStyleDeclaration.h"
#include "CSSStyleDeclaration.h"
#include "CSSValue.h"
#include "JSCSSStyleDeclaration.h"
#include "JSCSSValue.h"
#include "JSSVGAnimatedBoolean.h"
#include "JSSVGAnimatedLength.h"
#include "JSSVGAnimatedString.h"
#include "JSSVGAnimatedTransformList.h"
#include "JSSVGElement.h"
#include "JSSVGMatrix.h"
#include "JSSVGRect.h"
#include "JSSVGStringList.h"
#include "PlatformString.h"
#include "SVGElement.h"
#include "SVGLineElement.h"
#include "SVGStringList.h"

using namespace KJS;

namespace WebCore {

/* Hash table */

static const HashEntry JSSVGLineElementTableEntries[] =
{
    { "xmllang", JSSVGLineElement::XmllangAttrNum, DontDelete, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "xmlspace", JSSVGLineElement::XmlspaceAttrNum, DontDelete, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "transform", JSSVGLineElement::TransformAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "externalResourcesRequired", JSSVGLineElement::ExternalResourcesRequiredAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "x1", JSSVGLineElement::X1AttrNum, DontDelete|ReadOnly, 0, &JSSVGLineElementTableEntries[17] },
    { "x2", JSSVGLineElement::X2AttrNum, DontDelete|ReadOnly, 0, &JSSVGLineElementTableEntries[15] },
    { "requiredExtensions", JSSVGLineElement::RequiredExtensionsAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "requiredFeatures", JSSVGLineElement::RequiredFeaturesAttrNum, DontDelete|ReadOnly, 0, &JSSVGLineElementTableEntries[16] },
    { 0, 0, 0, 0, 0 },
    { "style", JSSVGLineElement::StyleAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "y1", JSSVGLineElement::Y1AttrNum, DontDelete|ReadOnly, 0, 0 },
    { "farthestViewportElement", JSSVGLineElement::FarthestViewportElementAttrNum, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "y2", JSSVGLineElement::Y2AttrNum, DontDelete|ReadOnly, 0, 0 },
    { "systemLanguage", JSSVGLineElement::SystemLanguageAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "className", JSSVGLineElement::ClassNameAttrNum, DontDelete|ReadOnly, 0, &JSSVGLineElementTableEntries[18] },
    { "nearestViewportElement", JSSVGLineElement::NearestViewportElementAttrNum, DontDelete|ReadOnly, 0, 0 }
};

static const HashTable JSSVGLineElementTable = 
{
    2, 19, JSSVGLineElementTableEntries, 15
};

/* Hash table for prototype */

static const HashEntry JSSVGLineElementPrototypeTableEntries[] =
{
    { "getPresentationAttribute", JSSVGLineElement::GetPresentationAttributeFuncNum, DontDelete|Function, 1, 0 },
    { "hasExtension", JSSVGLineElement::HasExtensionFuncNum, DontDelete|Function, 1, 0 },
    { "getCTM", JSSVGLineElement::GetCTMFuncNum, DontDelete|Function, 0, 0 },
    { "getScreenCTM", JSSVGLineElement::GetScreenCTMFuncNum, DontDelete|Function, 0, 0 },
    { "getTransformToElement", JSSVGLineElement::GetTransformToElementFuncNum, DontDelete|Function, 1, 0 },
    { "getBBox", JSSVGLineElement::GetBBoxFuncNum, DontDelete|Function, 0, 0 }
};

static const HashTable JSSVGLineElementPrototypeTable = 
{
    2, 6, JSSVGLineElementPrototypeTableEntries, 6
};

const ClassInfo JSSVGLineElementPrototype::info = { "SVGLineElementPrototype", 0, &JSSVGLineElementPrototypeTable, 0 };

JSObject* JSSVGLineElementPrototype::self(ExecState* exec)
{
    return KJS::cacheGlobalObject<JSSVGLineElementPrototype>(exec, "[[JSSVGLineElement.prototype]]");
}

bool JSSVGLineElementPrototype::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticFunctionSlot<JSSVGLineElementPrototypeFunction, JSObject>(exec, &JSSVGLineElementPrototypeTable, this, propertyName, slot);
}

const ClassInfo JSSVGLineElement::info = { "SVGLineElement", &JSSVGElement::info, &JSSVGLineElementTable, 0 };

JSSVGLineElement::JSSVGLineElement(ExecState* exec, SVGLineElement* impl)
    : JSSVGElement(exec, impl)
{
    setPrototype(JSSVGLineElementPrototype::self(exec));
}

bool JSSVGLineElement::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGLineElement, JSSVGElement>(exec, &JSSVGLineElementTable, this, propertyName, slot);
}

JSValue* JSSVGLineElement::getValueProperty(ExecState* exec, int token) const
{
    switch (token) {
    case X1AttrNum: {
        SVGLineElement* imp = static_cast<SVGLineElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->x1Animated();
        return toJS(exec, obj.get(), imp);
    }
    case Y1AttrNum: {
        SVGLineElement* imp = static_cast<SVGLineElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->y1Animated();
        return toJS(exec, obj.get(), imp);
    }
    case X2AttrNum: {
        SVGLineElement* imp = static_cast<SVGLineElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->x2Animated();
        return toJS(exec, obj.get(), imp);
    }
    case Y2AttrNum: {
        SVGLineElement* imp = static_cast<SVGLineElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->y2Animated();
        return toJS(exec, obj.get(), imp);
    }
    case RequiredFeaturesAttrNum: {
        SVGLineElement* imp = static_cast<SVGLineElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->requiredFeatures()), imp);
    }
    case RequiredExtensionsAttrNum: {
        SVGLineElement* imp = static_cast<SVGLineElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->requiredExtensions()), imp);
    }
    case SystemLanguageAttrNum: {
        SVGLineElement* imp = static_cast<SVGLineElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->systemLanguage()), imp);
    }
    case XmllangAttrNum: {
        SVGLineElement* imp = static_cast<SVGLineElement*>(impl());

        return jsString(imp->xmllang());
    }
    case XmlspaceAttrNum: {
        SVGLineElement* imp = static_cast<SVGLineElement*>(impl());

        return jsString(imp->xmlspace());
    }
    case ExternalResourcesRequiredAttrNum: {
        SVGLineElement* imp = static_cast<SVGLineElement*>(impl());

        RefPtr<SVGAnimatedBoolean> obj = imp->externalResourcesRequiredAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case ClassNameAttrNum: {
        SVGLineElement* imp = static_cast<SVGLineElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->classNameAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case StyleAttrNum: {
        SVGLineElement* imp = static_cast<SVGLineElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->style()));
    }
    case TransformAttrNum: {
        SVGLineElement* imp = static_cast<SVGLineElement*>(impl());

        RefPtr<SVGAnimatedTransformList> obj = imp->transformAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case NearestViewportElementAttrNum: {
        SVGLineElement* imp = static_cast<SVGLineElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->nearestViewportElement()));
    }
    case FarthestViewportElementAttrNum: {
        SVGLineElement* imp = static_cast<SVGLineElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->farthestViewportElement()));
    }
    }
    return 0;
}

void JSSVGLineElement::put(ExecState* exec, const Identifier& propertyName, JSValue* value, int attr)
{
    lookupPut<JSSVGLineElement, JSSVGElement>(exec, propertyName, value, attr, &JSSVGLineElementTable, this);
}

void JSSVGLineElement::putValueProperty(ExecState* exec, int token, JSValue* value, int /*attr*/)
{
    switch (token) {
    case XmllangAttrNum: {
        SVGLineElement* imp = static_cast<SVGLineElement*>(impl());

        imp->setXmllang(value->toString(exec));
        break;
    }
    case XmlspaceAttrNum: {
        SVGLineElement* imp = static_cast<SVGLineElement*>(impl());

        imp->setXmlspace(value->toString(exec));
        break;
    }
    }
}

JSValue* JSSVGLineElementPrototypeFunction::callAsFunction(ExecState* exec, JSObject* thisObj, const List& args)
{
    if (!thisObj->inherits(&JSSVGLineElement::info))
      return throwError(exec, TypeError);

    JSSVGLineElement* castedThisObj = static_cast<JSSVGLineElement*>(thisObj);
    SVGLineElement* imp = static_cast<SVGLineElement*>(castedThisObj->impl());

    switch (id) {
    case JSSVGLineElement::HasExtensionFuncNum: {
        String extension = args[0]->toString(exec);


        KJS::JSValue* result = jsBoolean(imp->hasExtension(extension));
        return result;
    }
    case JSSVGLineElement::GetPresentationAttributeFuncNum: {
        String name = args[0]->toString(exec);


        KJS::JSValue* result = toJS(exec, WTF::getPtr(imp->getPresentationAttribute(name)));
        return result;
    }
    case JSSVGLineElement::GetBBoxFuncNum: {


        KJS::JSValue* result = toJS(exec, new JSSVGPODTypeWrapperCreatorReadOnly<FloatRect>(imp->getBBox()), imp);
        return result;
    }
    case JSSVGLineElement::GetCTMFuncNum: {


        KJS::JSValue* result = toJS(exec, new JSSVGPODTypeWrapperCreatorReadOnly<AffineTransform>(imp->getCTM()), imp);
        return result;
    }
    case JSSVGLineElement::GetScreenCTMFuncNum: {


        KJS::JSValue* result = toJS(exec, new JSSVGPODTypeWrapperCreatorReadOnly<AffineTransform>(imp->getScreenCTM()), imp);
        return result;
    }
    case JSSVGLineElement::GetTransformToElementFuncNum: {
        ExceptionCode ec = 0;
        SVGElement* element = toSVGElement(args[0]);


        KJS::JSValue* result = toJS(exec, new JSSVGPODTypeWrapperCreatorReadOnly<AffineTransform>(imp->getTransformToElement(element, ec)), imp);
        setDOMException(exec, ec);
        return result;
    }
    }
    return 0;
}

}

#endif // ENABLE(SVG)
