/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"


#if ENABLE(SVG)

#include "Document.h"
#include "Frame.h"
#include "SVGDocumentExtensions.h"
#include "SVGElement.h"
#include "SVGAnimatedTemplate.h"
#include "JSSVGForeignObjectElement.h"

#include <wtf/GetPtr.h>

#include "CSSMutableStyleDeclaration.h"
#include "CSSStyleDeclaration.h"
#include "CSSValue.h"
#include "JSCSSStyleDeclaration.h"
#include "JSCSSValue.h"
#include "JSSVGAnimatedBoolean.h"
#include "JSSVGAnimatedLength.h"
#include "JSSVGAnimatedString.h"
#include "JSSVGAnimatedTransformList.h"
#include "JSSVGElement.h"
#include "JSSVGMatrix.h"
#include "JSSVGRect.h"
#include "JSSVGStringList.h"
#include "PlatformString.h"
#include "SVGElement.h"
#include "SVGForeignObjectElement.h"
#include "SVGStringList.h"

using namespace KJS;

namespace WebCore {

/* Hash table */

static const HashEntry JSSVGForeignObjectElementTableEntries[] =
{
    { "xmllang", JSSVGForeignObjectElement::XmllangAttrNum, DontDelete, 0, 0 },
    { "y", JSSVGForeignObjectElement::YAttrNum, DontDelete|ReadOnly, 0, &JSSVGForeignObjectElementTableEntries[15] },
    { "height", JSSVGForeignObjectElement::HeightAttrNum, DontDelete|ReadOnly, 0, &JSSVGForeignObjectElementTableEntries[18] },
    { 0, 0, 0, 0, 0 },
    { "transform", JSSVGForeignObjectElement::TransformAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "externalResourcesRequired", JSSVGForeignObjectElement::ExternalResourcesRequiredAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "className", JSSVGForeignObjectElement::ClassNameAttrNum, DontDelete|ReadOnly, 0, &JSSVGForeignObjectElementTableEntries[19] },
    { 0, 0, 0, 0, 0 },
    { "x", JSSVGForeignObjectElement::XAttrNum, DontDelete|ReadOnly, 0, &JSSVGForeignObjectElementTableEntries[16] },
    { "requiredFeatures", JSSVGForeignObjectElement::RequiredFeaturesAttrNum, DontDelete|ReadOnly, 0, &JSSVGForeignObjectElementTableEntries[17] },
    { 0, 0, 0, 0, 0 },
    { "style", JSSVGForeignObjectElement::StyleAttrNum, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "farthestViewportElement", JSSVGForeignObjectElement::FarthestViewportElementAttrNum, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "width", JSSVGForeignObjectElement::WidthAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "requiredExtensions", JSSVGForeignObjectElement::RequiredExtensionsAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "systemLanguage", JSSVGForeignObjectElement::SystemLanguageAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "xmlspace", JSSVGForeignObjectElement::XmlspaceAttrNum, DontDelete, 0, 0 },
    { "nearestViewportElement", JSSVGForeignObjectElement::NearestViewportElementAttrNum, DontDelete|ReadOnly, 0, 0 }
};

static const HashTable JSSVGForeignObjectElementTable = 
{
    2, 20, JSSVGForeignObjectElementTableEntries, 15
};

/* Hash table for prototype */

static const HashEntry JSSVGForeignObjectElementPrototypeTableEntries[] =
{
    { "getPresentationAttribute", JSSVGForeignObjectElement::GetPresentationAttributeFuncNum, DontDelete|Function, 1, 0 },
    { "hasExtension", JSSVGForeignObjectElement::HasExtensionFuncNum, DontDelete|Function, 1, 0 },
    { "getCTM", JSSVGForeignObjectElement::GetCTMFuncNum, DontDelete|Function, 0, 0 },
    { "getScreenCTM", JSSVGForeignObjectElement::GetScreenCTMFuncNum, DontDelete|Function, 0, 0 },
    { "getTransformToElement", JSSVGForeignObjectElement::GetTransformToElementFuncNum, DontDelete|Function, 1, 0 },
    { "getBBox", JSSVGForeignObjectElement::GetBBoxFuncNum, DontDelete|Function, 0, 0 }
};

static const HashTable JSSVGForeignObjectElementPrototypeTable = 
{
    2, 6, JSSVGForeignObjectElementPrototypeTableEntries, 6
};

const ClassInfo JSSVGForeignObjectElementPrototype::info = { "SVGForeignObjectElementPrototype", 0, &JSSVGForeignObjectElementPrototypeTable, 0 };

JSObject* JSSVGForeignObjectElementPrototype::self(ExecState* exec)
{
    return KJS::cacheGlobalObject<JSSVGForeignObjectElementPrototype>(exec, "[[JSSVGForeignObjectElement.prototype]]");
}

bool JSSVGForeignObjectElementPrototype::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticFunctionSlot<JSSVGForeignObjectElementPrototypeFunction, JSObject>(exec, &JSSVGForeignObjectElementPrototypeTable, this, propertyName, slot);
}

const ClassInfo JSSVGForeignObjectElement::info = { "SVGForeignObjectElement", &JSSVGElement::info, &JSSVGForeignObjectElementTable, 0 };

JSSVGForeignObjectElement::JSSVGForeignObjectElement(ExecState* exec, SVGForeignObjectElement* impl)
    : JSSVGElement(exec, impl)
{
    setPrototype(JSSVGForeignObjectElementPrototype::self(exec));
}

bool JSSVGForeignObjectElement::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGForeignObjectElement, JSSVGElement>(exec, &JSSVGForeignObjectElementTable, this, propertyName, slot);
}

JSValue* JSSVGForeignObjectElement::getValueProperty(ExecState* exec, int token) const
{
    switch (token) {
    case XAttrNum: {
        SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->xAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case YAttrNum: {
        SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->yAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case WidthAttrNum: {
        SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->widthAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case HeightAttrNum: {
        SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->heightAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case RequiredFeaturesAttrNum: {
        SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->requiredFeatures()), imp);
    }
    case RequiredExtensionsAttrNum: {
        SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->requiredExtensions()), imp);
    }
    case SystemLanguageAttrNum: {
        SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->systemLanguage()), imp);
    }
    case XmllangAttrNum: {
        SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(impl());

        return jsString(imp->xmllang());
    }
    case XmlspaceAttrNum: {
        SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(impl());

        return jsString(imp->xmlspace());
    }
    case ExternalResourcesRequiredAttrNum: {
        SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(impl());

        RefPtr<SVGAnimatedBoolean> obj = imp->externalResourcesRequiredAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case ClassNameAttrNum: {
        SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->classNameAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case StyleAttrNum: {
        SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->style()));
    }
    case TransformAttrNum: {
        SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(impl());

        RefPtr<SVGAnimatedTransformList> obj = imp->transformAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case NearestViewportElementAttrNum: {
        SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->nearestViewportElement()));
    }
    case FarthestViewportElementAttrNum: {
        SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->farthestViewportElement()));
    }
    }
    return 0;
}

void JSSVGForeignObjectElement::put(ExecState* exec, const Identifier& propertyName, JSValue* value, int attr)
{
    lookupPut<JSSVGForeignObjectElement, JSSVGElement>(exec, propertyName, value, attr, &JSSVGForeignObjectElementTable, this);
}

void JSSVGForeignObjectElement::putValueProperty(ExecState* exec, int token, JSValue* value, int /*attr*/)
{
    switch (token) {
    case XmllangAttrNum: {
        SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(impl());

        imp->setXmllang(value->toString(exec));
        break;
    }
    case XmlspaceAttrNum: {
        SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(impl());

        imp->setXmlspace(value->toString(exec));
        break;
    }
    }
}

JSValue* JSSVGForeignObjectElementPrototypeFunction::callAsFunction(ExecState* exec, JSObject* thisObj, const List& args)
{
    if (!thisObj->inherits(&JSSVGForeignObjectElement::info))
      return throwError(exec, TypeError);

    JSSVGForeignObjectElement* castedThisObj = static_cast<JSSVGForeignObjectElement*>(thisObj);
    SVGForeignObjectElement* imp = static_cast<SVGForeignObjectElement*>(castedThisObj->impl());

    switch (id) {
    case JSSVGForeignObjectElement::HasExtensionFuncNum: {
        String extension = args[0]->toString(exec);


        KJS::JSValue* result = jsBoolean(imp->hasExtension(extension));
        return result;
    }
    case JSSVGForeignObjectElement::GetPresentationAttributeFuncNum: {
        String name = args[0]->toString(exec);


        KJS::JSValue* result = toJS(exec, WTF::getPtr(imp->getPresentationAttribute(name)));
        return result;
    }
    case JSSVGForeignObjectElement::GetBBoxFuncNum: {


        KJS::JSValue* result = toJS(exec, new JSSVGPODTypeWrapperCreatorReadOnly<FloatRect>(imp->getBBox()), imp);
        return result;
    }
    case JSSVGForeignObjectElement::GetCTMFuncNum: {


        KJS::JSValue* result = toJS(exec, new JSSVGPODTypeWrapperCreatorReadOnly<AffineTransform>(imp->getCTM()), imp);
        return result;
    }
    case JSSVGForeignObjectElement::GetScreenCTMFuncNum: {


        KJS::JSValue* result = toJS(exec, new JSSVGPODTypeWrapperCreatorReadOnly<AffineTransform>(imp->getScreenCTM()), imp);
        return result;
    }
    case JSSVGForeignObjectElement::GetTransformToElementFuncNum: {
        ExceptionCode ec = 0;
        SVGElement* element = toSVGElement(args[0]);


        KJS::JSValue* result = toJS(exec, new JSSVGPODTypeWrapperCreatorReadOnly<AffineTransform>(imp->getTransformToElement(element, ec)), imp);
        setDOMException(exec, ec);
        return result;
    }
    }
    return 0;
}

}

#endif // ENABLE(SVG)
