/* ANSI-C code produced by gperf version 3.0.3 */
/* Command-line: gperf -a -L ANSI-C -C -G -c -o -t -N findEntity -D -s 2 /home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf  */
/* Computed positions: -k'1-3,5,$' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"

/*   This file is part of the KDE libraries
  
     Copyright (C) 1999 Lars Knoll (knoll@mpi-hd.mpg.de)
  
     This library is free software; you can redistribute it and/or
     modify it under the terms of the GNU Library General Public
     License as published by the Free Software Foundation; either
     version 2 of the License, or (at your option) any later version.
  
     This library is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
     Library General Public License for more details.
  
     You should have received a copy of the GNU Library General Public License
     along with this library; see the file COPYING.LIB.  If not, write to
     the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
     Boston, MA 02110-1301, USA.
  
  ----------------------------------------------------------------------------
  
    HTMLEntityNames.gperf: input file to generate a hash table for entities
    HTMLEntityNames.c: DO NOT EDIT! generated by the command
    "gperf -a -L "ANSI-C" -C -G -c -o -t -k '*' -NfindEntity -D -s 2 HTMLEntityNames.gperf > entities.c"   
    from HTMLEntityNames.gperf 

*/
#line 30 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
struct Entity {
    const char *name;
    int code;
};

#define TOTAL_KEYWORDS 262
#define MIN_WORD_LENGTH 2
#define MAX_WORD_LENGTH 8
#define MIN_HASH_VALUE 3
#define MAX_HASH_VALUE 666
/* maximum key range = 664, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash (register const char *str, register unsigned int len)
{
  static const unsigned short asso_values[] =
    {
      667, 667, 667, 667, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667, 667, 667, 667, 667,  90,
      140, 120,   0, 667, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667,  85, 265, 110,   0,  60,
        0,  25,   5,  70, 667,   5,  45,   0,  90, 135,
        5,  30,  85,  10,   5,  50,  25, 667,  10,  55,
       40, 667, 667, 667, 667, 667, 667,  10,  35,  60,
       30,   5, 105, 160, 135,   0, 250,   0, 195, 110,
       25,  15,   0, 205,  95,   0,  15,  25,  70,  15,
       15,  75,   0,   0, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667, 667, 667, 667, 667, 667,
      667, 667, 667, 667, 667, 667, 667
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[4]];
      /*FALLTHROUGH*/
      case 4:
      case 3:
        hval += asso_values[(unsigned char)str[2]];
      /*FALLTHROUGH*/
      case 2:
        hval += asso_values[(unsigned char)str[1]+1];
      /*FALLTHROUGH*/
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval + asso_values[(unsigned char)str[len - 1]];
}

static const struct Entity wordlist[] =
  {
#line 228 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"phi", 0x03c6},
#line 79 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Phi", 0x03a6},
#line 233 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"prime", 0x2032},
#line 236 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"psi", 0x03c8},
#line 235 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"prop", 0x221d},
#line 81 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Prime", 0x2033},
#line 275 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"thinsp", 0x2009},
#line 82 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Psi", 0x03a8},
#line 143 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ensp", 0x2002},
#line 171 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"iota", 0x03b9},
#line 272 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"there4", 0x2234},
#line 142 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"emsp", 0x2003},
#line 90 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Theta", 0x0398},
#line 107 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"amp", 38},
#line 254 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"sdot", 0x22c5},
#line 279 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"trade", 0x2122},
#line 173 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"isin", 0x2208},
#line 273 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"theta", 0x03b8},
#line 170 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"int", 0x222b},
#line 234 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"prod", 0x220f},
#line 168 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"image", 0x2111},
#line 221 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"otimes", 0x2297},
#line 146 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"eta", 0x03b7},
#line 202 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"not", 0x00ac},
#line 175 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"kappa", 0x03ba},
#line 123 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"chi", 0x03c7},
#line 64 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Kappa", 0x039a},
#line 205 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"nsup", 0x2285},
#line 213 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"omega", 0x03c9},
#line 264 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"sup", 0x2283},
#line 113 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"atilde", 0x00e3},
#line 268 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"supe", 0x2287},
#line 102 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"acute", 0x00b4},
#line 220 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"otilde", 0x00f5},
#line 57 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"GT", 62},
#line 276 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"thorn", 0x00fe},
#line 253 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"scaron", 0x0161},
#line 108 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"and", 0x2227},
#line 198 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"nbsp", 0x00a0},
#line 232 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"pound", 0x00a3},
#line 206 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ntilde", 0x00f1},
#line 89 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Tau", 0x03a4},
#line 203 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"notin", 0x2209},
#line 86 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Scaron", 0x0160},
#line 67 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Mu", 0x039c},
#line 119 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"cap", 0x2229},
#line 62 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Iota", 0x0399},
#line 65 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"LT", 60},
#line 271 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"tau", 0x03c4},
#line 204 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"nsub", 0x2284},
#line 112 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"asymp", 0x2248},
#line 55 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Eta", 0x0397},
#line 216 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"or", 0x2228},
#line 47 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Chi", 0x03a7},
#line 262 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"sube", 0x2286},
#line 150 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"exist", 0x2203},
#line 85 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Rho", 0x03a1},
#line 197 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"nabla", 0x2207},
#line 164 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"iacute", 0x00ed},
#line 207 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"nu", 0x03bd},
#line 50 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ETH", 0x00d0},
#line 138 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"eacute", 0x00e9},
#line 248 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"rho", 0x03c1},
#line 100 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"aacute", 0x00e1},
#line 129 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"cup", 0x222a},
#line 294 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"zeta", 0x03b6},
#line 208 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"oacute", 0x00f3},
#line 200 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ne", 0x2260},
#line 84 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"REG", 0x00ae},
#line 127 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"copy", 0x00a9},
#line 212 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"oline", 0x203e},
#line 172 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"iquest", 0x00bf},
#line 261 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"sub", 0x2282},
#line 223 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"para", 0x00b6},
#line 106 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"alpha", 0x03b1},
#line 281 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"uacute", 0x00fa},
#line 274 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"thetasym", 0x03d1},
#line 224 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"part", 0x2202},
#line 42 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Atilde", 0x00c3},
#line 256 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"shy", 0x00ad},
#line 217 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ordf", 0x00aa},
#line 165 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"icirc", 0x00ee},
#line 68 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Ntilde", 0x00d1},
#line 218 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ordm", 0x00ba},
#line 139 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ecirc", 0x00ea},
#line 265 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"sup1", 0x00b9},
#line 101 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"acirc", 0x00e2},
#line 250 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"rsaquo", 0x203a},
#line 214 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"omicron", 0x03bf},
#line 116 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"beta", 0x03b2},
#line 209 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ocirc", 0x00f4},
#line 91 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Uacute", 0x00da},
#line 99 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Zeta", 0x0396},
#line 169 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"infin", 0x221e},
#line 97 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Yacute", 0x00dd},
#line 45 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"COPY", 0x00a9},
#line 283 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ucirc", 0x00fb},
#line 51 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Eacute", 0x00c9},
#line 255 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"sect", 0x00a7},
#line 141 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"empty", 0x2205},
#line 69 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Nu", 0x039d},
#line 36 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"AMP", 38},
#line 149 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"euro", 0x20ac},
#line 74 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Omega", 0x03a9},
#line 59 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Iacute", 0x00cd},
#line 267 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"sup3", 0x00b3},
#line 58 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Gamma", 0x0393},
#line 291 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"yacute", 0x00fd},
#line 186 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"loz", 0x25ca},
#line 83 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"QUOT", 34},
#line 125 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"clubs", 0x2663},
#line 77 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Otilde", 0x00d5},
#line 159 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"gt", 62},
#line 227 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"perp", 0x22a5},
#line 92 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Ucirc", 0x00db},
#line 37 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Aacute", 0x00c1},
#line 196 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"mu", 0x03bc},
#line 122 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"cent", 0x00a2},
#line 154 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"frac14", 0x00bc},
#line 266 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"sup2", 0x00b2},
#line 52 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Ecirc", 0x00ca},
#line 117 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"brvbar", 0x00a6},
#line 40 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Alpha", 0x0391},
#line 289 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"weierp", 0x2118},
#line 60 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Icirc", 0x00ce},
#line 260 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"spades", 0x2660},
#line 185 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"lowast", 0x2217},
#line 292 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"yen", 0x00a5},
#line 110 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"apos", 0x0027},
#line 66 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Lambda", 0x039b},
#line 190 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"lt", 60},
#line 38 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Acirc", 0x00c2},
#line 155 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"frac34", 0x00be},
#line 105 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"alefsym", 0x2135},
#line 151 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"fnof", 0x0192},
#line 225 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"percnt", 0x0025},
#line 126 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"cong", 0x2245},
#line 229 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"pi", 0x03c0},
#line 282 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"uarr", 0x2191},
#line 71 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Oacute", 0x00d3},
#line 80 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Pi", 0x03a0},
#line 133 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"darr", 0x2193},
#line 130 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"curren", 0x00a4},
#line 96 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Xi", 0x039e},
#line 128 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"crarr", 0x21b5},
#line 188 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"lsaquo", 0x2039},
#line 290 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"xi", 0x03be},
#line 269 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"supl", 0x00b9},
#line 145 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"equiv", 0x2261},
#line 162 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"hearts", 0x2665},
#line 158 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ge", 0x2265},
#line 231 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"plusmn", 0x00b1},
#line 201 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ni", 0x220b},
#line 115 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"bdquo", 0x201e},
#line 239 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"radic", 0x221a},
#line 75 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Omicron", 0x039f},
#line 72 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Ocirc", 0x00d4},
#line 263 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"sum", 0x2211},
#line 296 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"zwnj", 0x200c},
#line 136 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"diams", 0x2666},
#line 120 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ccedil", 0x00e7},
#line 252 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"sbquo", 0x201a},
#line 48 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Dagger", 0x2021},
#line 147 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"eth", 0x00f0},
#line 191 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"macr", 0x00af},
#line 183 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"le", 0x2264},
#line 237 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"quot", 34},
#line 167 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"igrave", 0x00ec},
#line 199 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ndash", 0x2013},
#line 140 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"egrave", 0x00e8},
#line 240 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"rang", 0x3009},
#line 104 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"agrave", 0x00e0},
#line 242 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"rarr", 0x2192},
#line 49 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Delta", 0x0394},
#line 211 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ograve", 0x00f2},
#line 157 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"gamma", 0x03b3},
#line 132 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"dagger", 0x2020},
#line 111 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"aring", 0x00e5},
#line 284 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ugrave", 0x00f9},
#line 244 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"rdquo", 0x201d},
#line 46 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Ccedil", 0x00c7},
#line 109 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ang", 0x2220},
#line 251 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"rsquo", 0x2019},
#line 153 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"frac12", 0x00bd},
#line 135 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"delta", 0x03b4},
#line 93 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Ugrave", 0x00d9},
#line 161 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"harr", 0x2194},
#line 219 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"oslash", 0x00f8},
#line 241 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"raquo", 0x00bb},
#line 53 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Egrave", 0x00c8},
#line 174 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"iuml", 0x00ef},
#line 278 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"times", 0x00d7},
#line 61 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Igrave", 0x00cc},
#line 148 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"euml", 0x00eb},
#line 177 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"lambda", 0x03bb},
#line 114 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"auml", 0x00e4},
#line 195 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"minus", 0x2212},
#line 137 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"divide", 0x00f7},
#line 230 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"piv", 0x03d6},
#line 222 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ouml", 0x00f6},
#line 88 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"THORN", 0x00de},
#line 39 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Agrave", 0x00c0},
#line 44 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Beta", 0x0392},
#line 192 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"mdash", 0x2014},
#line 226 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"permil", 0x2030},
#line 288 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"uuml", 0x00fc},
#line 245 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"real", 0x211c},
#line 41 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Aring", 0x00c5},
#line 187 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"lrm", 0x200e},
#line 178 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"lang", 0x3008},
#line 215 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"oplus", 0x2295},
#line 180 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"larr", 0x2190},
#line 194 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"middot", 0x00b7},
#line 249 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"rlm", 0x200f},
#line 95 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Uuml", 0x00dc},
#line 98 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Yuml", 0x0178},
#line 257 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"sigma", 0x03c3},
#line 144 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"epsilon", 0x03b5},
#line 56 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Euml", 0x00cb},
#line 182 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"ldquo", 0x201c},
#line 163 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"hellip", 0x2026},
#line 285 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"uml", 0x00a8},
#line 87 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Sigma", 0x03a3},
#line 73 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Ograve", 0x00d2},
#line 63 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Iuml", 0x00cf},
#line 189 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"lsquo", 0x2018},
#line 293 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"yuml", 0x00ff},
#line 193 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"micro", 0x00b5},
#line 287 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"upsilon", 0x03c5},
#line 134 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"deg", 0x00b0},
#line 43 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Auml", 0x00c4},
#line 124 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"circ", 0x02c6},
#line 179 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"laquo", 0x00ab},
#line 259 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"sim", 0x223c},
#line 277 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"tilde", 0x02dc},
#line 94 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Upsilon", 0x03a5},
#line 280 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"uArr", 0x21d1},
#line 76 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Oslash", 0x00d8},
#line 131 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"dArr", 0x21d3},
#line 54 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Epsilon", 0x0395},
#line 118 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"bull", 0x2022},
#line 286 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"upsih", 0x03d2},
#line 156 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"frasl", 0x2044},
#line 78 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"Ouml", 0x00d6},
#line 166 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"iexcl", 0x00a1},
#line 295 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"zwj", 0x200d},
#line 270 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"szlig", 0x00df},
#line 246 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"reg", 0x00ae},
#line 243 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"rceil", 0x2309},
#line 258 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"sigmaf", 0x03c2},
#line 238 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"rArr", 0x21d2},
#line 247 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"rfloor", 0x230b},
#line 121 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"cedil", 0x00b8},
#line 160 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"hArr", 0x21d4},
#line 152 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"forall", 0x2200},
#line 35 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"AElig", 0x00c6},
#line 181 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"lceil", 0x2308},
#line 103 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"aelig", 0x00e6},
#line 210 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"oelig", 0x0153},
#line 176 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"lArr", 0x21d0},
#line 70 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"OElig", 0x0152},
#line 184 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"
    {"lfloor", 0x230a}
  };

static const short lookup[] =
  {
     -1,  -1,  -1,   0,  -1,  -1,  -1,  -1,   1,  -1,
     -1,  -1,  -1,  -1,  -1,   2,  -1,  -1,   3,   4,
      5,   6,  -1,   7,   8,  -1,  -1,  -1,  -1,   9,
     -1,  10,  -1,  -1,  11,  12,  -1,  -1,  13,  14,
     15,  -1,  -1,  -1,  16,  17,  -1,  -1,  18,  19,
     20,  21,  -1,  22,  -1,  -1,  -1,  -1,  23,  -1,
     24,  -1,  -1,  25,  -1,  26,  -1,  -1,  -1,  27,
     28,  -1,  -1,  29,  -1,  -1,  30,  -1,  -1,  31,
     32,  33,  34,  -1,  -1,  35,  36,  -1,  37,  38,
     39,  40,  -1,  41,  -1,  42,  43,  44,  45,  46,
     -1,  -1,  47,  48,  49,  50,  -1,  -1,  51,  -1,
     -1,  -1,  52,  53,  54,  55,  -1,  -1,  56,  -1,
     57,  58,  59,  60,  -1,  -1,  61,  -1,  62,  -1,
     -1,  63,  -1,  64,  65,  -1,  66,  67,  68,  69,
     70,  71,  -1,  72,  73,  74,  75,  -1,  76,  77,
     -1,  78,  -1,  79,  80,  81,  82,  -1,  -1,  83,
     84,  -1,  -1,  -1,  85,  86,  87,  88,  -1,  89,
     90,  91,  -1,  -1,  92,  93,  94,  -1,  -1,  95,
     96,  97,  -1,  -1,  98,  99,  -1, 100, 101, 102,
    103, 104,  -1,  -1, 105, 106, 107,  -1, 108, 109,
    110, 111, 112,  -1, 113, 114, 115, 116,  -1, 117,
     -1, 118,  -1,  -1, 119, 120, 121,  -1,  -1,  -1,
    122, 123,  -1,  -1,  -1, 124, 125,  -1,  -1,  -1,
     -1, 126,  -1, 127, 128,  -1, 129, 130,  -1,  -1,
    131, 132, 133,  -1, 134,  -1, 135,  -1,  -1, 136,
     -1,  -1, 137,  -1, 138,  -1, 139, 140,  -1, 141,
     -1, 142, 143,  -1,  -1, 144, 145, 146,  -1, 147,
    148, 149, 150,  -1,  -1,  -1, 151, 152,  -1,  -1,
    153,  -1,  -1,  -1,  -1, 154,  -1, 155,  -1,  -1,
    156,  -1,  -1, 157, 158, 159, 160,  -1,  -1,  -1,
    161, 162,  -1, 163, 164,  -1,  -1, 165,  -1, 166,
     -1, 167,  -1,  -1,  -1, 168, 169,  -1,  -1, 170,
     -1, 171,  -1,  -1, 172, 173, 174,  -1,  -1,  -1,
    175, 176,  -1,  -1,  -1, 177, 178,  -1,  -1,  -1,
    179,  -1,  -1,  -1,  -1,  -1, 180,  -1, 181,  -1,
    182, 183,  -1,  -1,  -1, 184,  -1,  -1,  -1,  -1,
     -1, 185,  -1,  -1, 186,  -1, 187,  -1,  -1,  -1,
    188, 189,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 190,
    191, 192,  -1,  -1, 193,  -1, 194,  -1,  -1, 195,
    196, 197,  -1, 198, 199, 200, 201,  -1,  -1, 202,
    203, 204,  -1,  -1, 205,  -1,  -1,  -1,  -1, 206,
    207,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 208, 209,
    210,  -1,  -1,  -1, 211,  -1, 212,  -1, 213, 214,
     -1,  -1,  -1,  -1, 215, 216,  -1, 217,  -1, 218,
    219, 220,  -1, 221,  -1, 222, 223,  -1,  -1, 224,
    225,  -1,  -1,  -1, 226, 227,  -1, 228, 229,  -1,
     -1,  -1,  -1,  -1, 230,  -1,  -1,  -1,  -1, 231,
    232,  -1,  -1, 233,  -1, 234,  -1,  -1,  -1,  -1,
     -1,  -1, 235,  -1, 236,  -1, 237,  -1,  -1, 238,
     -1,  -1, 239,  -1,  -1,  -1,  -1,  -1,  -1, 240,
     -1,  -1,  -1,  -1,  -1, 241,  -1,  -1,  -1,  -1,
    242,  -1,  -1,  -1, 243, 244,  -1,  -1, 245,  -1,
    246,  -1,  -1, 247,  -1, 248,  -1,  -1,  -1,  -1,
     -1, 249,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1, 250,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 251,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    252,  -1,  -1,  -1, 253,  -1, 254,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 255,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 256,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 257,  -1,  -1,  -1,  -1,
    258,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1, 259, 260,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 261
  };

#ifdef __GNUC__
__inline
#ifdef __GNUC_STDC_INLINE__
__attribute__ ((__gnu_inline__))
#endif
#endif
const struct Entity *
findEntity (register const char *str, register unsigned int len)
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        {
          register int index = lookup[key];

          if (index >= 0)
            {
              register const char *s = wordlist[index].name;

              if (*str == *s && !strncmp (str + 1, s + 1, len - 1) && s[len] == '\0')
                return &wordlist[index];
            }
        }
    }
  return 0;
}
#line 297 "/home/zhangjipeng/macross-browser/source/webcore/html/HTMLEntityNames.gperf"

