/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"


#if ENABLE(SVG)

#include "Document.h"
#include "Frame.h"
#include "SVGDocumentExtensions.h"
#include "SVGElement.h"
#include "SVGAnimatedTemplate.h"
#include "JSSVGMatrix.h"

#include <wtf/GetPtr.h>


using namespace KJS;

namespace WebCore {

/* Hash table */

static const HashEntry JSSVGMatrixTableEntries[] =
{
    { 0, 0, 0, 0, 0 },
    { "b", JSSVGMatrix::BAttrNum, DontDelete, 0, &JSSVGMatrixTableEntries[7] },
    { 0, 0, 0, 0, 0 },
    { "c", JSSVGMatrix::CAttrNum, DontDelete, 0, &JSSVGMatrixTableEntries[6] },
    { "f", JSSVGMatrix::FAttrNum, DontDelete, 0, 0 },
    { "a", JSSVGMatrix::AAttrNum, DontDelete, 0, 0 },
    { "d", JSSVGMatrix::DAttrNum, DontDelete, 0, 0 },
    { "e", JSSVGMatrix::EAttrNum, DontDelete, 0, 0 }
};

static const HashTable JSSVGMatrixTable = 
{
    2, 8, JSSVGMatrixTableEntries, 6
};

/* Hash table for prototype */

static const HashEntry JSSVGMatrixPrototypeTableEntries[] =
{
    { "skewX", JSSVGMatrix::SkewXFuncNum, DontDelete|Function, 1, 0 },
    { 0, 0, 0, 0, 0 },
    { "rotateFromVector", JSSVGMatrix::RotateFromVectorFuncNum, DontDelete|Function, 2, 0 },
    { 0, 0, 0, 0, 0 },
    { "flipX", JSSVGMatrix::FlipXFuncNum, DontDelete|Function, 0, 0 },
    { "multiply", JSSVGMatrix::MultiplyFuncNum, DontDelete|Function, 1, 0 },
    { 0, 0, 0, 0, 0 },
    { "inverse", JSSVGMatrix::InverseFuncNum, DontDelete|Function, 0, &JSSVGMatrixPrototypeTableEntries[11] },
    { "rotate", JSSVGMatrix::RotateFuncNum, DontDelete|Function, 1, 0 },
    { "scaleNonUniform", JSSVGMatrix::ScaleNonUniformFuncNum, DontDelete|Function, 2, &JSSVGMatrixPrototypeTableEntries[12] },
    { "scale", JSSVGMatrix::ScaleFuncNum, DontDelete|Function, 1, &JSSVGMatrixPrototypeTableEntries[13] },
    { "translate", JSSVGMatrix::TranslateFuncNum, DontDelete|Function, 2, 0 },
    { "flipY", JSSVGMatrix::FlipYFuncNum, DontDelete|Function, 0, 0 },
    { "skewY", JSSVGMatrix::SkewYFuncNum, DontDelete|Function, 1, 0 }
};

static const HashTable JSSVGMatrixPrototypeTable = 
{
    2, 14, JSSVGMatrixPrototypeTableEntries, 11
};

const ClassInfo JSSVGMatrixPrototype::info = { "SVGMatrixPrototype", 0, &JSSVGMatrixPrototypeTable, 0 };

JSObject* JSSVGMatrixPrototype::self(ExecState* exec)
{
    return KJS::cacheGlobalObject<JSSVGMatrixPrototype>(exec, "[[JSSVGMatrix.prototype]]");
}

bool JSSVGMatrixPrototype::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticFunctionSlot<JSSVGMatrixPrototypeFunction, JSObject>(exec, &JSSVGMatrixPrototypeTable, this, propertyName, slot);
}

const ClassInfo JSSVGMatrix::info = { "SVGMatrix", 0, &JSSVGMatrixTable, 0 };

JSSVGMatrix::JSSVGMatrix(ExecState* exec, JSSVGPODTypeWrapper<AffineTransform>* impl, SVGElement* context)
    : m_context(context)
    , m_impl(impl)
{
    setPrototype(JSSVGMatrixPrototype::self(exec));
}

JSSVGMatrix::~JSSVGMatrix()
{
    ScriptInterpreter::forgetDOMObject(m_impl.get());

}

bool JSSVGMatrix::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGMatrix, KJS::DOMObject>(exec, &JSSVGMatrixTable, this, propertyName, slot);
}

JSValue* JSSVGMatrix::getValueProperty(ExecState* exec, int token) const
{
    switch (token) {
    case AAttrNum: {
        AffineTransform imp(*impl());

        return jsNumber(imp.a());
    }
    case BAttrNum: {
        AffineTransform imp(*impl());

        return jsNumber(imp.b());
    }
    case CAttrNum: {
        AffineTransform imp(*impl());

        return jsNumber(imp.c());
    }
    case DAttrNum: {
        AffineTransform imp(*impl());

        return jsNumber(imp.d());
    }
    case EAttrNum: {
        AffineTransform imp(*impl());

        return jsNumber(imp.e());
    }
    case FAttrNum: {
        AffineTransform imp(*impl());

        return jsNumber(imp.f());
    }
    }
    return 0;
}

void JSSVGMatrix::put(ExecState* exec, const Identifier& propertyName, JSValue* value, int attr)
{
    lookupPut<JSSVGMatrix, KJS::DOMObject>(exec, propertyName, value, attr, &JSSVGMatrixTable, this);
}

void JSSVGMatrix::putValueProperty(ExecState* exec, int token, JSValue* value, int /*attr*/)
{
    switch (token) {
    case AAttrNum: {
        AffineTransform imp(*impl());

        imp.setA(value->toNumber(exec));
        m_impl->commitChange(exec, imp);
        break;
    }
    case BAttrNum: {
        AffineTransform imp(*impl());

        imp.setB(value->toNumber(exec));
        m_impl->commitChange(exec, imp);
        break;
    }
    case CAttrNum: {
        AffineTransform imp(*impl());

        imp.setC(value->toNumber(exec));
        m_impl->commitChange(exec, imp);
        break;
    }
    case DAttrNum: {
        AffineTransform imp(*impl());

        imp.setD(value->toNumber(exec));
        m_impl->commitChange(exec, imp);
        break;
    }
    case EAttrNum: {
        AffineTransform imp(*impl());

        imp.setE(value->toNumber(exec));
        m_impl->commitChange(exec, imp);
        break;
    }
    case FAttrNum: {
        AffineTransform imp(*impl());

        imp.setF(value->toNumber(exec));
        m_impl->commitChange(exec, imp);
        break;
    }
    }
    if (context())
        context()->notifyAttributeChange();
}

JSValue* JSSVGMatrixPrototypeFunction::callAsFunction(ExecState* exec, JSObject* thisObj, const List& args)
{
    if (!thisObj->inherits(&JSSVGMatrix::info))
      return throwError(exec, TypeError);

    JSSVGMatrix* castedThisObj = static_cast<JSSVGMatrix*>(thisObj);
    JSSVGPODTypeWrapper<AffineTransform>* wrapper = castedThisObj->impl();
    AffineTransform imp(*wrapper);

    switch (id) {
    case JSSVGMatrix::MultiplyFuncNum: {
        return castedThisObj->multiply(exec, args);
    }
    case JSSVGMatrix::InverseFuncNum: {
        return castedThisObj->inverse(exec, args);
    }
    case JSSVGMatrix::TranslateFuncNum: {
        return castedThisObj->translate(exec, args);
    }
    case JSSVGMatrix::ScaleFuncNum: {
        return castedThisObj->scale(exec, args);
    }
    case JSSVGMatrix::ScaleNonUniformFuncNum: {
        return castedThisObj->scaleNonUniform(exec, args);
    }
    case JSSVGMatrix::RotateFuncNum: {
        return castedThisObj->rotate(exec, args);
    }
    case JSSVGMatrix::RotateFromVectorFuncNum: {
        return castedThisObj->rotateFromVector(exec, args);
    }
    case JSSVGMatrix::FlipXFuncNum: {
        return castedThisObj->flipX(exec, args);
    }
    case JSSVGMatrix::FlipYFuncNum: {
        return castedThisObj->flipY(exec, args);
    }
    case JSSVGMatrix::SkewXFuncNum: {
        return castedThisObj->skewX(exec, args);
    }
    case JSSVGMatrix::SkewYFuncNum: {
        return castedThisObj->skewY(exec, args);
    }
    }
    (void)imp;
    return 0;
}
KJS::JSValue* toJS(KJS::ExecState* exec, JSSVGPODTypeWrapper<AffineTransform>* obj, SVGElement* context)
{
    return KJS::cacheSVGDOMObject<JSSVGPODTypeWrapper<AffineTransform>, JSSVGMatrix>(exec, obj, context);
}
AffineTransform toSVGMatrix(KJS::JSValue* val)
{
    return val->isObject(&JSSVGMatrix::info) ? (AffineTransform) *static_cast<JSSVGMatrix*>(val)->impl() : AffineTransform();
}

}

#endif // ENABLE(SVG)
