/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"


#if ENABLE(SVG) && ENABLE(SVG_EXPERIMENTAL_FEATURES)

#include "Document.h"
#include "Frame.h"
#include "SVGDocumentExtensions.h"
#include "SVGElement.h"
#include "SVGAnimatedTemplate.h"
#include "JSSVGFETurbulenceElement.h"

#include <wtf/GetPtr.h>

#include "CSSMutableStyleDeclaration.h"
#include "CSSStyleDeclaration.h"
#include "CSSValue.h"
#include "JSCSSStyleDeclaration.h"
#include "JSCSSValue.h"
#include "JSSVGAnimatedEnumeration.h"
#include "JSSVGAnimatedInteger.h"
#include "JSSVGAnimatedLength.h"
#include "JSSVGAnimatedNumber.h"
#include "JSSVGAnimatedString.h"
#include "SVGFETurbulenceElement.h"

using namespace KJS;

namespace WebCore {

/* Hash table */

static const HashEntry JSSVGFETurbulenceElementTableEntries[] =
{
    { "baseFrequencyY", JSSVGFETurbulenceElement::BaseFrequencyYAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "baseFrequencyX", JSSVGFETurbulenceElement::BaseFrequencyXAttrNum, DontDelete|ReadOnly, 0, &JSSVGFETurbulenceElementTableEntries[15] },
    { "style", JSSVGFETurbulenceElement::StyleAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "stitchTiles", JSSVGFETurbulenceElement::StitchTilesAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "numOctaves", JSSVGFETurbulenceElement::NumOctavesAttrNum, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "result", JSSVGFETurbulenceElement::ResultAttrNum, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "className", JSSVGFETurbulenceElement::ClassNameAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "x", JSSVGFETurbulenceElement::XAttrNum, DontDelete|ReadOnly, 0, &JSSVGFETurbulenceElementTableEntries[16] },
    { 0, 0, 0, 0, 0 },
    { "seed", JSSVGFETurbulenceElement::SeedAttrNum, DontDelete|ReadOnly, 0, &JSSVGFETurbulenceElementTableEntries[14] },
    { "y", JSSVGFETurbulenceElement::YAttrNum, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "type", JSSVGFETurbulenceElement::TypeAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "width", JSSVGFETurbulenceElement::WidthAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "height", JSSVGFETurbulenceElement::HeightAttrNum, DontDelete|ReadOnly, 0, &JSSVGFETurbulenceElementTableEntries[17] },
    { "constructor", JSSVGFETurbulenceElement::ConstructorAttrNum, DontDelete|DontEnum|ReadOnly, 0, 0 }
};

static const HashTable JSSVGFETurbulenceElementTable = 
{
    2, 18, JSSVGFETurbulenceElementTableEntries, 14
};

/* Hash table for constructor */

static const HashEntry JSSVGFETurbulenceElementConstructorTableEntries[] =
{
    { 0, 0, 0, 0, 0 },
    { "SVG_TURBULENCE_TYPE_UNKNOWN", WebCore::SVG_TURBULENCE_TYPE_UNKNOWN, DontDelete|ReadOnly, 0, &JSSVGFETurbulenceElementConstructorTableEntries[8] },
    { "SVG_TURBULENCE_TYPE_FRACTALNOISE", WebCore::SVG_TURBULENCE_TYPE_FRACTALNOISE, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "SVG_TURBULENCE_TYPE_TURBULENCE", WebCore::SVG_TURBULENCE_TYPE_TURBULENCE, DontDelete|ReadOnly, 0, &JSSVGFETurbulenceElementConstructorTableEntries[6] },
    { "SVG_STITCHTYPE_UNKNOWN", WebCore::SVG_STITCHTYPE_UNKNOWN, DontDelete|ReadOnly, 0, &JSSVGFETurbulenceElementConstructorTableEntries[7] },
    { "SVG_STITCHTYPE_STITCH", WebCore::SVG_STITCHTYPE_STITCH, DontDelete|ReadOnly, 0, 0 },
    { "SVG_STITCHTYPE_NOSTITCH", WebCore::SVG_STITCHTYPE_NOSTITCH, DontDelete|ReadOnly, 0, 0 }
};

static const HashTable JSSVGFETurbulenceElementConstructorTable = 
{
    2, 9, JSSVGFETurbulenceElementConstructorTableEntries, 6
};

class JSSVGFETurbulenceElementConstructor : public DOMObject {
public:
    JSSVGFETurbulenceElementConstructor(ExecState* exec)
    {
        setPrototype(exec->lexicalInterpreter()->builtinObjectPrototype());
        putDirect(exec->propertyNames().prototype, JSSVGFETurbulenceElementPrototype::self(exec), None);
    }
    virtual bool getOwnPropertySlot(ExecState*, const Identifier&, PropertySlot&);
    JSValue* getValueProperty(ExecState*, int token) const;
    virtual const ClassInfo* classInfo() const { return &info; }
    static const ClassInfo info;

    virtual bool implementsHasInstance() const { return true; }
};

const ClassInfo JSSVGFETurbulenceElementConstructor::info = { "SVGFETurbulenceElementConstructor", 0, &JSSVGFETurbulenceElementConstructorTable, 0 };

bool JSSVGFETurbulenceElementConstructor::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGFETurbulenceElementConstructor, DOMObject>(exec, &JSSVGFETurbulenceElementConstructorTable, this, propertyName, slot);
}

JSValue* JSSVGFETurbulenceElementConstructor::getValueProperty(ExecState*, int token) const
{
    // The token is the numeric value of its associated constant
    return jsNumber(token);
}

/* Hash table for prototype */

static const HashEntry JSSVGFETurbulenceElementPrototypeTableEntries[] =
{
    { 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "SVG_TURBULENCE_TYPE_UNKNOWN", WebCore::SVG_TURBULENCE_TYPE_UNKNOWN, DontDelete|ReadOnly, 0, &JSSVGFETurbulenceElementPrototypeTableEntries[7] },
    { "SVG_STITCHTYPE_STITCH", WebCore::SVG_STITCHTYPE_STITCH, DontDelete|ReadOnly, 0, &JSSVGFETurbulenceElementPrototypeTableEntries[9] },
    { "SVG_TURBULENCE_TYPE_FRACTALNOISE", WebCore::SVG_TURBULENCE_TYPE_FRACTALNOISE, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "SVG_TURBULENCE_TYPE_TURBULENCE", WebCore::SVG_TURBULENCE_TYPE_TURBULENCE, DontDelete|ReadOnly, 0, &JSSVGFETurbulenceElementPrototypeTableEntries[8] },
    { "SVG_STITCHTYPE_UNKNOWN", WebCore::SVG_STITCHTYPE_UNKNOWN, DontDelete|ReadOnly, 0, &JSSVGFETurbulenceElementPrototypeTableEntries[10] },
    { "SVG_STITCHTYPE_NOSTITCH", WebCore::SVG_STITCHTYPE_NOSTITCH, DontDelete|ReadOnly, 0, 0 },
    { "getPresentationAttribute", JSSVGFETurbulenceElement::GetPresentationAttributeFuncNum, DontDelete|Function, 1, 0 }
};

static const HashTable JSSVGFETurbulenceElementPrototypeTable = 
{
    2, 11, JSSVGFETurbulenceElementPrototypeTableEntries, 7
};

const ClassInfo JSSVGFETurbulenceElementPrototype::info = { "SVGFETurbulenceElementPrototype", 0, &JSSVGFETurbulenceElementPrototypeTable, 0 };

JSObject* JSSVGFETurbulenceElementPrototype::self(ExecState* exec)
{
    return KJS::cacheGlobalObject<JSSVGFETurbulenceElementPrototype>(exec, "[[JSSVGFETurbulenceElement.prototype]]");
}

bool JSSVGFETurbulenceElementPrototype::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticPropertySlot<JSSVGFETurbulenceElementPrototypeFunction, JSSVGFETurbulenceElementPrototype, JSObject>(exec, &JSSVGFETurbulenceElementPrototypeTable, this, propertyName, slot);
}

JSValue* JSSVGFETurbulenceElementPrototype::getValueProperty(ExecState*, int token) const
{
    // The token is the numeric value of its associated constant
    return jsNumber(token);
}

const ClassInfo JSSVGFETurbulenceElement::info = { "SVGFETurbulenceElement", &JSSVGElement::info, &JSSVGFETurbulenceElementTable, 0 };

JSSVGFETurbulenceElement::JSSVGFETurbulenceElement(ExecState* exec, SVGFETurbulenceElement* impl)
    : JSSVGElement(exec, impl)
{
    setPrototype(JSSVGFETurbulenceElementPrototype::self(exec));
}

bool JSSVGFETurbulenceElement::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGFETurbulenceElement, JSSVGElement>(exec, &JSSVGFETurbulenceElementTable, this, propertyName, slot);
}

JSValue* JSSVGFETurbulenceElement::getValueProperty(ExecState* exec, int token) const
{
    switch (token) {
    case BaseFrequencyXAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());

        RefPtr<SVGAnimatedNumber> obj = imp->baseFrequencyXAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case BaseFrequencyYAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());

        RefPtr<SVGAnimatedNumber> obj = imp->baseFrequencyYAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case NumOctavesAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());

        RefPtr<SVGAnimatedInteger> obj = imp->numOctavesAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case SeedAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());

        RefPtr<SVGAnimatedNumber> obj = imp->seedAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case StitchTilesAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());

        RefPtr<SVGAnimatedEnumeration> obj = imp->stitchTilesAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case TypeAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());

        RefPtr<SVGAnimatedEnumeration> obj = imp->typeAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case XAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->xAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case YAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->yAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case WidthAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->widthAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case HeightAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->heightAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case ResultAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->resultAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case ClassNameAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->classNameAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case StyleAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->style()));
    }
    case ConstructorAttrNum:
        return getConstructor(exec);
    }
    return 0;
}

JSValue* JSSVGFETurbulenceElement::getConstructor(ExecState* exec)
{
    return KJS::cacheGlobalObject<JSSVGFETurbulenceElementConstructor>(exec, "[[SVGFETurbulenceElement.constructor]]");
}
JSValue* JSSVGFETurbulenceElementPrototypeFunction::callAsFunction(ExecState* exec, JSObject* thisObj, const List& args)
{
    if (!thisObj->inherits(&JSSVGFETurbulenceElement::info))
      return throwError(exec, TypeError);

    JSSVGFETurbulenceElement* castedThisObj = static_cast<JSSVGFETurbulenceElement*>(thisObj);
    SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(castedThisObj->impl());

    switch (id) {
    case JSSVGFETurbulenceElement::GetPresentationAttributeFuncNum: {
        String name = args[0]->toString(exec);


        KJS::JSValue* result = toJS(exec, WTF::getPtr(imp->getPresentationAttribute(name)));
        return result;
    }
    }
    return 0;
}

}

#endif // ENABLE(SVG) && ENABLE(SVG_EXPERIMENTAL_FEATURES)
