/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"


#if ENABLE(SVG) && ENABLE(SVG_EXPERIMENTAL_FEATURES)

#include "Document.h"
#include "Frame.h"
#include "SVGDocumentExtensions.h"
#include "SVGElement.h"
#include "SVGAnimatedTemplate.h"
#include "JSSVGFEBlendElement.h"

#include <wtf/GetPtr.h>

#include "CSSMutableStyleDeclaration.h"
#include "CSSStyleDeclaration.h"
#include "CSSValue.h"
#include "JSCSSStyleDeclaration.h"
#include "JSCSSValue.h"
#include "JSSVGAnimatedEnumeration.h"
#include "JSSVGAnimatedLength.h"
#include "JSSVGAnimatedString.h"
#include "SVGFEBlendElement.h"

using namespace KJS;

namespace WebCore {

/* Hash table */

static const HashEntry JSSVGFEBlendElementTableEntries[] =
{
    { 0, 0, 0, 0, 0 },
    { "x", JSSVGFEBlendElement::XAttrNum, DontDelete|ReadOnly, 0, &JSSVGFEBlendElementTableEntries[14] },
    { 0, 0, 0, 0, 0 },
    { "height", JSSVGFEBlendElement::HeightAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "mode", JSSVGFEBlendElement::ModeAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "in2", JSSVGFEBlendElement::In2AttrNum, DontDelete|ReadOnly, 0, &JSSVGFEBlendElementTableEntries[12] },
    { "y", JSSVGFEBlendElement::YAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "in1", JSSVGFEBlendElement::In1AttrNum, DontDelete|ReadOnly, 0, &JSSVGFEBlendElementTableEntries[11] },
    { 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "result", JSSVGFEBlendElement::ResultAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "width", JSSVGFEBlendElement::WidthAttrNum, DontDelete|ReadOnly, 0, &JSSVGFEBlendElementTableEntries[13] },
    { "className", JSSVGFEBlendElement::ClassNameAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "style", JSSVGFEBlendElement::StyleAttrNum, DontDelete|ReadOnly, 0, 0 },
    { "constructor", JSSVGFEBlendElement::ConstructorAttrNum, DontDelete|DontEnum|ReadOnly, 0, 0 }
};

static const HashTable JSSVGFEBlendElementTable = 
{
    2, 15, JSSVGFEBlendElementTableEntries, 11
};

/* Hash table for constructor */

static const HashEntry JSSVGFEBlendElementConstructorTableEntries[] =
{
    { "SVG_FEBLEND_MODE_NORMAL", WebCore::SVG_FEBLEND_MODE_NORMAL, DontDelete|ReadOnly, 0, &JSSVGFEBlendElementConstructorTableEntries[6] },
    { "SVG_FEBLEND_MODE_UNKNOWN", WebCore::SVG_FEBLEND_MODE_UNKNOWN, DontDelete|ReadOnly, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "SVG_FEBLEND_MODE_MULTIPLY", WebCore::SVG_FEBLEND_MODE_MULTIPLY, DontDelete|ReadOnly, 0, &JSSVGFEBlendElementConstructorTableEntries[7] },
    { "SVG_FEBLEND_MODE_SCREEN", WebCore::SVG_FEBLEND_MODE_SCREEN, DontDelete|ReadOnly, 0, 0 },
    { "SVG_FEBLEND_MODE_DARKEN", WebCore::SVG_FEBLEND_MODE_DARKEN, DontDelete|ReadOnly, 0, &JSSVGFEBlendElementConstructorTableEntries[8] },
    { "SVG_FEBLEND_MODE_LIGHTEN", WebCore::SVG_FEBLEND_MODE_LIGHTEN, DontDelete|ReadOnly, 0, 0 }
};

static const HashTable JSSVGFEBlendElementConstructorTable = 
{
    2, 9, JSSVGFEBlendElementConstructorTableEntries, 6
};

class JSSVGFEBlendElementConstructor : public DOMObject {
public:
    JSSVGFEBlendElementConstructor(ExecState* exec)
    {
        setPrototype(exec->lexicalInterpreter()->builtinObjectPrototype());
        putDirect(exec->propertyNames().prototype, JSSVGFEBlendElementPrototype::self(exec), None);
    }
    virtual bool getOwnPropertySlot(ExecState*, const Identifier&, PropertySlot&);
    JSValue* getValueProperty(ExecState*, int token) const;
    virtual const ClassInfo* classInfo() const { return &info; }
    static const ClassInfo info;

    virtual bool implementsHasInstance() const { return true; }
};

const ClassInfo JSSVGFEBlendElementConstructor::info = { "SVGFEBlendElementConstructor", 0, &JSSVGFEBlendElementConstructorTable, 0 };

bool JSSVGFEBlendElementConstructor::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGFEBlendElementConstructor, DOMObject>(exec, &JSSVGFEBlendElementConstructorTable, this, propertyName, slot);
}

JSValue* JSSVGFEBlendElementConstructor::getValueProperty(ExecState*, int token) const
{
    // The token is the numeric value of its associated constant
    return jsNumber(token);
}

/* Hash table for prototype */

static const HashEntry JSSVGFEBlendElementPrototypeTableEntries[] =
{
    { "SVG_FEBLEND_MODE_DARKEN", WebCore::SVG_FEBLEND_MODE_DARKEN, DontDelete|ReadOnly, 0, &JSSVGFEBlendElementPrototypeTableEntries[7] },
    { "SVG_FEBLEND_MODE_SCREEN", WebCore::SVG_FEBLEND_MODE_SCREEN, DontDelete|ReadOnly, 0, 0 },
    { "SVG_FEBLEND_MODE_UNKNOWN", WebCore::SVG_FEBLEND_MODE_UNKNOWN, DontDelete|ReadOnly, 0, &JSSVGFEBlendElementPrototypeTableEntries[8] },
    { 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0 },
    { "SVG_FEBLEND_MODE_MULTIPLY", WebCore::SVG_FEBLEND_MODE_MULTIPLY, DontDelete|ReadOnly, 0, 0 },
    { "SVG_FEBLEND_MODE_NORMAL", WebCore::SVG_FEBLEND_MODE_NORMAL, DontDelete|ReadOnly, 0, 0 },
    { "SVG_FEBLEND_MODE_LIGHTEN", WebCore::SVG_FEBLEND_MODE_LIGHTEN, DontDelete|ReadOnly, 0, 0 },
    { "getPresentationAttribute", JSSVGFEBlendElement::GetPresentationAttributeFuncNum, DontDelete|Function, 1, 0 }
};

static const HashTable JSSVGFEBlendElementPrototypeTable = 
{
    2, 9, JSSVGFEBlendElementPrototypeTableEntries, 7
};

const ClassInfo JSSVGFEBlendElementPrototype::info = { "SVGFEBlendElementPrototype", 0, &JSSVGFEBlendElementPrototypeTable, 0 };

JSObject* JSSVGFEBlendElementPrototype::self(ExecState* exec)
{
    return KJS::cacheGlobalObject<JSSVGFEBlendElementPrototype>(exec, "[[JSSVGFEBlendElement.prototype]]");
}

bool JSSVGFEBlendElementPrototype::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticPropertySlot<JSSVGFEBlendElementPrototypeFunction, JSSVGFEBlendElementPrototype, JSObject>(exec, &JSSVGFEBlendElementPrototypeTable, this, propertyName, slot);
}

JSValue* JSSVGFEBlendElementPrototype::getValueProperty(ExecState*, int token) const
{
    // The token is the numeric value of its associated constant
    return jsNumber(token);
}

const ClassInfo JSSVGFEBlendElement::info = { "SVGFEBlendElement", &JSSVGElement::info, &JSSVGFEBlendElementTable, 0 };

JSSVGFEBlendElement::JSSVGFEBlendElement(ExecState* exec, SVGFEBlendElement* impl)
    : JSSVGElement(exec, impl)
{
    setPrototype(JSSVGFEBlendElementPrototype::self(exec));
}

bool JSSVGFEBlendElement::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGFEBlendElement, JSSVGElement>(exec, &JSSVGFEBlendElementTable, this, propertyName, slot);
}

JSValue* JSSVGFEBlendElement::getValueProperty(ExecState* exec, int token) const
{
    switch (token) {
    case In1AttrNum: {
        SVGFEBlendElement* imp = static_cast<SVGFEBlendElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->in1Animated();
        return toJS(exec, obj.get(), imp);
    }
    case In2AttrNum: {
        SVGFEBlendElement* imp = static_cast<SVGFEBlendElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->in2Animated();
        return toJS(exec, obj.get(), imp);
    }
    case ModeAttrNum: {
        SVGFEBlendElement* imp = static_cast<SVGFEBlendElement*>(impl());

        RefPtr<SVGAnimatedEnumeration> obj = imp->modeAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case XAttrNum: {
        SVGFEBlendElement* imp = static_cast<SVGFEBlendElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->xAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case YAttrNum: {
        SVGFEBlendElement* imp = static_cast<SVGFEBlendElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->yAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case WidthAttrNum: {
        SVGFEBlendElement* imp = static_cast<SVGFEBlendElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->widthAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case HeightAttrNum: {
        SVGFEBlendElement* imp = static_cast<SVGFEBlendElement*>(impl());

        RefPtr<SVGAnimatedLength> obj = imp->heightAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case ResultAttrNum: {
        SVGFEBlendElement* imp = static_cast<SVGFEBlendElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->resultAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case ClassNameAttrNum: {
        SVGFEBlendElement* imp = static_cast<SVGFEBlendElement*>(impl());

        RefPtr<SVGAnimatedString> obj = imp->classNameAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case StyleAttrNum: {
        SVGFEBlendElement* imp = static_cast<SVGFEBlendElement*>(impl());

        return toJS(exec, WTF::getPtr(imp->style()));
    }
    case ConstructorAttrNum:
        return getConstructor(exec);
    }
    return 0;
}

JSValue* JSSVGFEBlendElement::getConstructor(ExecState* exec)
{
    return KJS::cacheGlobalObject<JSSVGFEBlendElementConstructor>(exec, "[[SVGFEBlendElement.constructor]]");
}
JSValue* JSSVGFEBlendElementPrototypeFunction::callAsFunction(ExecState* exec, JSObject* thisObj, const List& args)
{
    if (!thisObj->inherits(&JSSVGFEBlendElement::info))
      return throwError(exec, TypeError);

    JSSVGFEBlendElement* castedThisObj = static_cast<JSSVGFEBlendElement*>(thisObj);
    SVGFEBlendElement* imp = static_cast<SVGFEBlendElement*>(castedThisObj->impl());

    switch (id) {
    case JSSVGFEBlendElement::GetPresentationAttributeFuncNum: {
        String name = args[0]->toString(exec);


        KJS::JSValue* result = toJS(exec, WTF::getPtr(imp->getPresentationAttribute(name)));
        return result;
    }
    }
    return 0;
}

}

#endif // ENABLE(SVG) && ENABLE(SVG_EXPERIMENTAL_FEATURES)
