WEBKIT_OPTION_BEGIN()

set(WEBKIT_API_VERSION "6.0")
set(WEBKIT_VERSION 6)
set(WEBKIT_VERSION_MAJOR 1)

add_definitions(-DWTF_PLATFORM_LIBUV=1)

find_package(Threads REQUIRED)
find_package(OpenGLES2 REQUIRED)

if (MSVC)
    include(OptionsMSVC)
else ()
    set(CMAKE_C_VISIBILITY_PRESET hidden)
    set(CMAKE_CXX_VISIBILITY_PRESET hidden)
    set(CMAKE_VISIBILITY_INLINES_HIDDEN ON)
endif ()

if(WIN32)
    set(LIB_PREFIX "")
    set(LIB_EXT "lib")
else()
    set(LIB_PREFIX "lib")
    set(LIB_EXT "so")
endif()

add_library(ICU::data UNKNOWN IMPORTED PUBLIC icudt)
set_target_properties(ICU::data PROPERTIES
    IMPORTED_LOCATION "${WORKSPACE_OUT}/lib/${LIB_PREFIX}icudt.${LIB_EXT}"
    INTERFACE_INCLUDE_DIRECTORIES "${WORKSPACE_OUT}/include"
    IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
)
add_library(ICU::i18n UNKNOWN IMPORTED PUBLIC icui18n)
set_target_properties(ICU::i18n PROPERTIES
    IMPORTED_LOCATION "${WORKSPACE_OUT}/lib/${LIB_PREFIX}icui18n.${LIB_EXT}"
    INTERFACE_INCLUDE_DIRECTORIES "${WORKSPACE_OUT}/include"
    IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
)
add_library(ICU::uc UNKNOWN IMPORTED PUBLIC icuuc)
set_target_properties(ICU::uc PROPERTIES
    IMPORTED_LOCATION "${WORKSPACE_OUT}/lib/${LIB_PREFIX}icuuc.${LIB_EXT}"
    INTERFACE_INCLUDE_DIRECTORIES "${WORKSPACE_OUT}/include"
    IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
)
add_library(LibXml2::LibXml2 UNKNOWN IMPORTED PUBLIC xml2)
set_target_properties(LibXml2::LibXml2 PROPERTIES
    IMPORTED_LOCATION "${WORKSPACE_OUT}/lib/${LIB_PREFIX}xml2.${LIB_EXT}"
    INTERFACE_INCLUDE_DIRECTORIES "${WORKSPACE_OUT}/include"
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
)
add_library(LibXslt::LibXslt UNKNOWN IMPORTED PUBLIC xslt)
set_target_properties(LibXml2::LibXml2 PROPERTIES
    IMPORTED_LOCATION "${WORKSPACE_OUT}/lib/${LIB_PREFIX}xslt.${LIB_EXT}"
    INTERFACE_INCLUDE_DIRECTORIES "${WORKSPACE_OUT}/include"
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
)
add_library(SQLite::SQLite3 UNKNOWN IMPORTED PUBLIC sqlite3)
set_target_properties(SQLite::SQLite3 PROPERTIES
    IMPORTED_LOCATION "${WORKSPACE_OUT}/lib/${LIB_PREFIX}sqlite3.${LIB_EXT}"
    INTERFACE_INCLUDE_DIRECTORIES "${WORKSPACE_OUT}/include"
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
)
add_library(ZLIB::ZLIB UNKNOWN IMPORTED PUBLIC zlib)
set_target_properties(ZLIB::ZLIB PROPERTIES
    IMPORTED_LOCATION "${WORKSPACE_OUT}/lib/${LIB_PREFIX}z.${LIB_EXT}"
    INTERFACE_INCLUDE_DIRECTORIES "${WORKSPACE_OUT}/include"
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
)

WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_REMOTE_INSPECTOR PRIVATE OFF)

if (WIN32)
    # FIXME: Enable FTL on Windows. https://bugs.webkit.org/show_bug.cgi?id=145366
    WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_FTL_JIT PRIVATE OFF)
    # FIXME: Port bmalloc to Windows. https://bugs.webkit.org/show_bug.cgi?id=143310
    #WEBKIT_OPTION_DEFAULT_PORT_VALUE(USE_SYSTEM_MALLOC PRIVATE ON)
    add_definitions(-DNOMINMAX)
    add_definitions(-D_WINDOWS -DWINVER=0x601 -D_WIN32_WINNT=0x601)
    add_definitions(-DUNICODE -D_UNICODE)
    set(USE_ANGLE_EGL ON)
endif ()

SET_AND_EXPOSE_TO_BUILD(USE_TEXTURE_MAPPER ON)
SET_AND_EXPOSE_TO_BUILD(USE_EGL ON)
SET_AND_EXPOSE_TO_BUILD(USE_COORDINATED_GRAPHICS ON)
SET_AND_EXPOSE_TO_BUILD(USE_NICOSIA ON)
SET_AND_EXPOSE_TO_BUILD(USE_ANGLE ${ENABLE_WEBGL})

if (NOT WIN32)
WEBKIT_APPEND_GLOBAL_COMPILER_FLAGS(-pipe)
endif ()

WEBKIT_OPTION_END()
