CC=gcc -g -static
CXX=g++ -g -static 
#CC=gcc -O2
INCPATH=-I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4
INC=${INCPATH} -I./ -I../ -I../include
CFLAGS=-DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -D_REENTRANT  
CXXFLAGS=-DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -D_REENTRANT 

SYSTEM_LIBS = -lQtGui -lQtCore -lfreetype -lpthread -lstdc++

objs = main.o callback.o interface.o functions.o popmenu.o

all: macross_app

macross_app : ${objs}
	libtool --mode=link ${CC} ${objs} ../source/libmacross.la -o $@ ${INC} ${SYSTEM_LIBS}

interface.o : interface.cpp
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

callback.o : callback.cpp
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

functions.o : qt4/functions.cpp
	${CXX} ${CXXFLAGS} -c $< -o $@ ${INC}

popmenu.o : qt4/popmenu.cpp
	${CXX} ${CXXFLAGS} -c $< -o $@ ${INC}

main.o : qt4/main.cpp
	${CXX} ${CXXFLAGS} -c $< -o $@ ${INC}

clean:
	rm *.o *.out macross_app
