WEBKIT_OPTION_BEGIN()

add_definitions(-DWTF_PLATFORM_LIBUV=1)

find_package(Threads REQUIRED)
find_package(OpenGLES2 REQUIRED)

if(WIN32)
set(LIB_PREFIX "")
set(LIB_EXT "lib")
else()
set(LIB_PREFIX "lib")
set(LIB_EXT "so")
endif()

add_library(ICU::data UNKNOWN IMPORTED PUBLIC icudt)
set_target_properties(ICU::data PROPERTIES
    IMPORTED_LOCATION "${WORKSPACE_OUT}/lib/${LIB_PREFIX}icudt.${LIB_EXT}"
    INTERFACE_INCLUDE_DIRECTORIES "${WORKSPACE_OUT}/include"
    IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
)
add_library(ICU::i18n UNKNOWN IMPORTED PUBLIC icui18n)
set_target_properties(ICU::i18n PROPERTIES
    IMPORTED_LOCATION "${WORKSPACE_OUT}/lib/${LIB_PREFIX}icui18n.${LIB_EXT}"
    INTERFACE_INCLUDE_DIRECTORIES "${WORKSPACE_OUT}/include"
    IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
)
add_library(ICU::uc UNKNOWN IMPORTED PUBLIC icuuc)
set_target_properties(ICU::uc PROPERTIES
    IMPORTED_LOCATION "${WORKSPACE_OUT}/lib/${LIB_PREFIX}icuuc.${LIB_EXT}"
    INTERFACE_INCLUDE_DIRECTORIES "${WORKSPACE_OUT}/include"
    IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
)
add_library(LibXml2::LibXml2 UNKNOWN IMPORTED PUBLIC xml2)
set_target_properties(LibXml2::LibXml2 PROPERTIES
    IMPORTED_LOCATION "${WORKSPACE_OUT}/lib/${LIB_PREFIX}xml2.${LIB_EXT}"
    INTERFACE_INCLUDE_DIRECTORIES "${WORKSPACE_OUT}/include"
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
)
add_library(LibXslt::LibXslt UNKNOWN IMPORTED PUBLIC xslt)
set_target_properties(LibXml2::LibXml2 PROPERTIES
    IMPORTED_LOCATION "${WORKSPACE_OUT}/lib/${LIB_PREFIX}xslt.${LIB_EXT}"
    INTERFACE_INCLUDE_DIRECTORIES "${WORKSPACE_OUT}/include"
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
)
add_library(SQLite::SQLite3 UNKNOWN IMPORTED PUBLIC sqlite3)
set_target_properties(SQLite::SQLite3 PROPERTIES
    IMPORTED_LOCATION "${WORKSPACE_OUT}/lib/${LIB_PREFIX}sqlite3.${LIB_EXT}"
    INTERFACE_INCLUDE_DIRECTORIES "${WORKSPACE_OUT}/include"
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
)
add_library(ZLIB::ZLIB UNKNOWN IMPORTED PUBLIC zlib)
set_target_properties(ZLIB::ZLIB PROPERTIES
    IMPORTED_LOCATION "${WORKSPACE_OUT}/lib/${LIB_PREFIX}zlib.${LIB_EXT}"
    INTERFACE_INCLUDE_DIRECTORIES "${WORKSPACE_OUT}/include"
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
)

WEBKIT_OPTION_END()
