name: Linux Make Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build project
      run: ./build_proj.sh
    - name: Setup Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: Setup APT
      run: /usr/bin/sudo apt-get update --fix-missing
    - name: install gperf flex bison make
      run: /usr/bin/sudo apt-get install gperf flex bison make libgtk2.0-dev libgles2-mesa-dev libegl1-mesa-dev
    - name: generate javascript binding
      run: python ./tools/generated_javascriptcore_files.py ./source/webkit-2.2.8/Source/JavaScriptCore ./source/webkit-2.2.8/Source/JavaScriptCore/Generated
    - name: generate webcore binding
      run: python ./tools/generated_webcore_files.py ./source/webkit-2.2.8/Source/WebCore Generated
    - name: build Debug      
      run: ulimit -s 65536 ; make -C ./proj/ -j16
    - name: build release
      run: ulimit -s 65536 ; make -C ./proj/ BUILDTYPE=Release -j16
