name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
       
    - name: Setup MSBuild.exe
      uses:  microsoft/setup-msbuild@v1.0.2
    
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7

    - name: Generate Project
      run: ./build_windows.bat
  
    - name: generate javascript binding
      run: .\\tools\\generated_javascriptcore_files.bat ./source/webkit-2.2.8/Source/JavaScriptCore ./source/webkit-2.2.8/Source/JavaScriptCore/Generated
   
    - name: generate webcore binding
      run: .\\tools\\generated_webcore_files.bat ./source/webkit-2.2.8/Source/WebCore Generated
    
    - name: Restore Project
      run: msbuild ./vcproj/all.sln /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
     
    - name: Build Solution
      run: msbuild ./vcproj/all.sln /p:Configuration=$env:Configuration -m
      env:
        Configuration: ${{ matrix.configuration }}   

